
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input								RESETN,
	//////////// SDCARD //////////
	output		          		SD_CLK,
	output 		          		SD_CMD,
	input 		     				SD_DAT0,
	output 		     				SD_DAT3,

	//////////// UART ///////////
	output							UART_TXD,
	input								UART_RXD,
	
	//////////// GPIO, GPIO connect to GPIO Default //////////
	output							JTAG_TDO,
	input								JTAG_TCK,
	input								JTAG_TMS,
	input								JTAG_TDI

	//////////// HSMC, HSMC connect to HTG - HSMC to PIO Adaptor //////////
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	TopHarness TopHarness(
	  .sys_clock	 (CLOCK_50	),
	  .reset			 (!RESETN	),
	  // JTAG (4)
	  .jtag_TCK		 (JTAG_TCK 	),
	  .jtag_TMS		 (JTAG_TMS 	),
	  .jtag_TDI		 (JTAG_TDI 	),
	  .jtag_TDO		 (JTAG_TDO 	),
	  // SPI (4)
	  .sdio_clk 	 (SD_CLK		),
	  .sdio_cs		 (SD_CMD 	),
	  .sdio_dat_0	 (SD_DAT0	),
	  .sdio_dat_3	 (SD_DAT3	),
	  .flash_dat_1  (1'b1		),
	  // UART (2)
	  .uart_txd		 (UART_TXD	),
	  .uart_rxd		 (UART_RXD	),
	  // SerDes (20)
	  .serin_valid	 (1'b0		),
	  .serin_data0  (1'b0		),
	  .serin_data1  (1'b0		),
	  .serin_data2  (1'b0		),
	  .serin_data3  (1'b0		),
	  .serin_data4  (1'b0		),
	  .serin_data5  (1'b0		),
	  .serin_data6  (1'b0		),
	  .serin_data7  (1'b0		),
	  .serout_ready (1'b1		),
	  // GPIO (16)   
	  .gpio_gpio_i0 (1'b0		),
	  .gpio_gpio_i1 (1'b0		),
	  .gpio_gpio_i2 (1'b0		),
	  .gpio_gpio_i3 (1'b0		),
	  .gpio_gpio_i4 (1'b0		),
	  .gpio_gpio_i5 (1'b0		),
	  .gpio_gpio_i6 (1'b0		),
	  .gpio_gpio_i7 (1'b0		)
	);



//=======================================================
//  Structural coding
//=======================================================



endmodule
