// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module RoccCommandRouter(
  input         clock,
                reset,
                io_in_valid,
  input  [6:0]  io_in_bits_inst_funct,
  input  [4:0]  io_in_bits_inst_rs2,
                io_in_bits_inst_rs1,
  input         io_in_bits_inst_xd,
                io_in_bits_inst_xs1,
                io_in_bits_inst_xs2,
  input  [4:0]  io_in_bits_inst_rd,
  input  [6:0]  io_in_bits_inst_opcode,
  input  [63:0] io_in_bits_rs1,
                io_in_bits_rs2,
  input         io_in_bits_status_debug,
                io_in_bits_status_cease,
                io_in_bits_status_wfi,
  input  [31:0] io_in_bits_status_isa,
  input  [1:0]  io_in_bits_status_dprv,
                io_in_bits_status_prv,
  input         io_in_bits_status_gva,
                io_in_bits_status_tsr,
                io_in_bits_status_tw,
                io_in_bits_status_tvm,
                io_in_bits_status_mxr,
                io_in_bits_status_sum,
                io_in_bits_status_mprv,
  input  [1:0]  io_in_bits_status_fs,
                io_in_bits_status_mpp,
  input         io_in_bits_status_spp,
                io_in_bits_status_mpie,
                io_in_bits_status_spie,
                io_in_bits_status_mie,
                io_in_bits_status_sie,
                io_out_0_ready,
                io_out_1_ready,
                io_out_2_ready,
                io_out_3_ready,
  output        io_in_ready,
                io_out_0_valid,
  output [6:0]  io_out_0_bits_inst_funct,
  output [4:0]  io_out_0_bits_inst_rd,
  output [6:0]  io_out_0_bits_inst_opcode,
  output [63:0] io_out_0_bits_rs1,
  output        io_out_1_valid,
  output [6:0]  io_out_1_bits_inst_funct,
  output [4:0]  io_out_1_bits_inst_rd,
  output [6:0]  io_out_1_bits_inst_opcode,
  output [63:0] io_out_1_bits_rs1,
  output        io_out_2_valid,
  output [6:0]  io_out_2_bits_inst_funct,
  output [4:0]  io_out_2_bits_inst_rd,
  output [6:0]  io_out_2_bits_inst_opcode,
  output [63:0] io_out_2_bits_rs1,
  output        io_out_3_valid,
  output [6:0]  io_out_3_bits_inst_funct,
  output [4:0]  io_out_3_bits_inst_rd,
  output [6:0]  io_out_3_bits_inst_opcode,
  output [63:0] io_out_3_bits_rs1,
  output        io_busy
);

  wire        _cmd_io_deq_valid;	// @[Decoupled.scala:375:21]
  wire [6:0]  _cmd_io_deq_bits_inst_funct;	// @[Decoupled.scala:375:21]
  wire [4:0]  _cmd_io_deq_bits_inst_rd;	// @[Decoupled.scala:375:21]
  wire [6:0]  _cmd_io_deq_bits_inst_opcode;	// @[Decoupled.scala:375:21]
  wire [63:0] _cmd_io_deq_bits_rs1;	// @[Decoupled.scala:375:21]
  wire        cmdReadys_me = _cmd_io_deq_bits_inst_opcode == 7'hB;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41]
  wire        cmdReadys_0 = io_out_0_ready & cmdReadys_me;	// @[LazyRoCC.scala:396:41, :420:15]
  wire        cmdReadys_me_1 = _cmd_io_deq_bits_inst_opcode == 7'h2B;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41]
  wire        cmdReadys_1 = io_out_1_ready & cmdReadys_me_1;	// @[LazyRoCC.scala:396:41, :420:15]
  wire        cmdReadys_me_2 = _cmd_io_deq_bits_inst_opcode == 7'h5B;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41]
  wire        cmdReadys_2 = io_out_2_ready & cmdReadys_me_2;	// @[LazyRoCC.scala:396:41, :420:15]
  wire        cmdReadys_me_3 = _cmd_io_deq_bits_inst_opcode == 7'h7B;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41]
  wire        cmdReadys_3 = io_out_3_ready & cmdReadys_me_3;	// @[LazyRoCC.scala:396:41, :420:15]
  `ifndef SYNTHESIS	// @[LazyRoCC.scala:425:9]
    wire [2:0] _T_5 = {1'h0, {1'h0, cmdReadys_0} + {1'h0, cmdReadys_1}} + {1'h0, {1'h0, cmdReadys_2} + {1'h0, cmdReadys_3}};	// @[Bitwise.scala:51:90, LazyRoCC.scala:396:41, :420:15]
    always @(posedge clock) begin	// @[LazyRoCC.scala:425:9]
      if (~reset & (|(_T_5[2:1]))) begin	// @[Bitwise.scala:51:90, LazyRoCC.scala:425:{9,30}]
        if (`ASSERT_VERBOSE_COND_)	// @[LazyRoCC.scala:425:9]
          $error("Assertion failed: Custom opcode matched for more than one accelerator\n    at LazyRoCC.scala:425 assert(PopCount(cmdReadys) <= 1.U,\n");	// @[LazyRoCC.scala:425:9]
        if (`STOP_COND_)	// @[LazyRoCC.scala:425:9]
          $fatal;	// @[LazyRoCC.scala:425:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  Queue_21 cmd (	// @[Decoupled.scala:375:21]
    .clock                    (clock),
    .reset                    (reset),
    .io_enq_valid             (io_in_valid),
    .io_enq_bits_inst_funct   (io_in_bits_inst_funct),
    .io_enq_bits_inst_rs2     (io_in_bits_inst_rs2),
    .io_enq_bits_inst_rs1     (io_in_bits_inst_rs1),
    .io_enq_bits_inst_xd      (io_in_bits_inst_xd),
    .io_enq_bits_inst_xs1     (io_in_bits_inst_xs1),
    .io_enq_bits_inst_xs2     (io_in_bits_inst_xs2),
    .io_enq_bits_inst_rd      (io_in_bits_inst_rd),
    .io_enq_bits_inst_opcode  (io_in_bits_inst_opcode),
    .io_enq_bits_rs1          (io_in_bits_rs1),
    .io_enq_bits_rs2          (io_in_bits_rs2),
    .io_enq_bits_status_debug (io_in_bits_status_debug),
    .io_enq_bits_status_cease (io_in_bits_status_cease),
    .io_enq_bits_status_wfi   (io_in_bits_status_wfi),
    .io_enq_bits_status_isa   (io_in_bits_status_isa),
    .io_enq_bits_status_dprv  (io_in_bits_status_dprv),
    .io_enq_bits_status_prv   (io_in_bits_status_prv),
    .io_enq_bits_status_gva   (io_in_bits_status_gva),
    .io_enq_bits_status_tsr   (io_in_bits_status_tsr),
    .io_enq_bits_status_tw    (io_in_bits_status_tw),
    .io_enq_bits_status_tvm   (io_in_bits_status_tvm),
    .io_enq_bits_status_mxr   (io_in_bits_status_mxr),
    .io_enq_bits_status_sum   (io_in_bits_status_sum),
    .io_enq_bits_status_mprv  (io_in_bits_status_mprv),
    .io_enq_bits_status_fs    (io_in_bits_status_fs),
    .io_enq_bits_status_mpp   (io_in_bits_status_mpp),
    .io_enq_bits_status_spp   (io_in_bits_status_spp),
    .io_enq_bits_status_mpie  (io_in_bits_status_mpie),
    .io_enq_bits_status_spie  (io_in_bits_status_spie),
    .io_enq_bits_status_mie   (io_in_bits_status_mie),
    .io_enq_bits_status_sie   (io_in_bits_status_sie),
    .io_deq_ready             (cmdReadys_0 | cmdReadys_1 | cmdReadys_2 | cmdReadys_3),	// @[LazyRoCC.scala:420:15, :422:35]
    .io_enq_ready             (io_in_ready),
    .io_deq_valid             (_cmd_io_deq_valid),
    .io_deq_bits_inst_funct   (_cmd_io_deq_bits_inst_funct),
    .io_deq_bits_inst_rd      (_cmd_io_deq_bits_inst_rd),
    .io_deq_bits_inst_opcode  (_cmd_io_deq_bits_inst_opcode),
    .io_deq_bits_rs1          (_cmd_io_deq_bits_rs1)
  );
  assign io_out_0_valid = _cmd_io_deq_valid & cmdReadys_me;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41, :418:28]
  assign io_out_0_bits_inst_funct = _cmd_io_deq_bits_inst_funct;	// @[Decoupled.scala:375:21]
  assign io_out_0_bits_inst_rd = _cmd_io_deq_bits_inst_rd;	// @[Decoupled.scala:375:21]
  assign io_out_0_bits_inst_opcode = _cmd_io_deq_bits_inst_opcode;	// @[Decoupled.scala:375:21]
  assign io_out_0_bits_rs1 = _cmd_io_deq_bits_rs1;	// @[Decoupled.scala:375:21]
  assign io_out_1_valid = _cmd_io_deq_valid & cmdReadys_me_1;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41, :418:28]
  assign io_out_1_bits_inst_funct = _cmd_io_deq_bits_inst_funct;	// @[Decoupled.scala:375:21]
  assign io_out_1_bits_inst_rd = _cmd_io_deq_bits_inst_rd;	// @[Decoupled.scala:375:21]
  assign io_out_1_bits_inst_opcode = _cmd_io_deq_bits_inst_opcode;	// @[Decoupled.scala:375:21]
  assign io_out_1_bits_rs1 = _cmd_io_deq_bits_rs1;	// @[Decoupled.scala:375:21]
  assign io_out_2_valid = _cmd_io_deq_valid & cmdReadys_me_2;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41, :418:28]
  assign io_out_2_bits_inst_funct = _cmd_io_deq_bits_inst_funct;	// @[Decoupled.scala:375:21]
  assign io_out_2_bits_inst_rd = _cmd_io_deq_bits_inst_rd;	// @[Decoupled.scala:375:21]
  assign io_out_2_bits_inst_opcode = _cmd_io_deq_bits_inst_opcode;	// @[Decoupled.scala:375:21]
  assign io_out_2_bits_rs1 = _cmd_io_deq_bits_rs1;	// @[Decoupled.scala:375:21]
  assign io_out_3_valid = _cmd_io_deq_valid & cmdReadys_me_3;	// @[Decoupled.scala:375:21, LazyRoCC.scala:396:41, :418:28]
  assign io_out_3_bits_inst_funct = _cmd_io_deq_bits_inst_funct;	// @[Decoupled.scala:375:21]
  assign io_out_3_bits_inst_rd = _cmd_io_deq_bits_inst_rd;	// @[Decoupled.scala:375:21]
  assign io_out_3_bits_inst_opcode = _cmd_io_deq_bits_inst_opcode;	// @[Decoupled.scala:375:21]
  assign io_out_3_bits_rs1 = _cmd_io_deq_bits_rs1;	// @[Decoupled.scala:375:21]
  assign io_busy = _cmd_io_deq_valid;	// @[Decoupled.scala:375:21]
endmodule

