// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLB_1(
  input         clock,
                reset,
                io_req_valid,
  input  [39:0] io_req_bits_vaddr,
  input  [1:0]  io_req_bits_prv,
  input         io_sfence_valid,
                io_sfence_bits_rs1,
                io_sfence_bits_rs2,
  input  [38:0] io_sfence_bits_addr,
  input         io_ptw_req_ready,
                io_ptw_resp_valid,
                io_ptw_resp_bits_ae_ptw,
                io_ptw_resp_bits_ae_final,
                io_ptw_resp_bits_pf,
                io_ptw_resp_bits_gf,
                io_ptw_resp_bits_hr,
                io_ptw_resp_bits_hw,
                io_ptw_resp_bits_hx,
  input  [43:0] io_ptw_resp_bits_pte_ppn,
  input         io_ptw_resp_bits_pte_d,
                io_ptw_resp_bits_pte_a,
                io_ptw_resp_bits_pte_g,
                io_ptw_resp_bits_pte_u,
                io_ptw_resp_bits_pte_x,
                io_ptw_resp_bits_pte_w,
                io_ptw_resp_bits_pte_r,
                io_ptw_resp_bits_pte_v,
  input  [1:0]  io_ptw_resp_bits_level,
  input         io_ptw_resp_bits_homogeneous,
  input  [3:0]  io_ptw_ptbr_mode,
  input         io_ptw_status_debug,
                io_ptw_pmp_0_cfg_l,
  input  [1:0]  io_ptw_pmp_0_cfg_a,
  input         io_ptw_pmp_0_cfg_x,
                io_ptw_pmp_0_cfg_w,
                io_ptw_pmp_0_cfg_r,
  input  [29:0] io_ptw_pmp_0_addr,
  input  [31:0] io_ptw_pmp_0_mask,
  input         io_ptw_pmp_1_cfg_l,
  input  [1:0]  io_ptw_pmp_1_cfg_a,
  input         io_ptw_pmp_1_cfg_x,
                io_ptw_pmp_1_cfg_w,
                io_ptw_pmp_1_cfg_r,
  input  [29:0] io_ptw_pmp_1_addr,
  input  [31:0] io_ptw_pmp_1_mask,
  input         io_ptw_pmp_2_cfg_l,
  input  [1:0]  io_ptw_pmp_2_cfg_a,
  input         io_ptw_pmp_2_cfg_x,
                io_ptw_pmp_2_cfg_w,
                io_ptw_pmp_2_cfg_r,
  input  [29:0] io_ptw_pmp_2_addr,
  input  [31:0] io_ptw_pmp_2_mask,
  input         io_ptw_pmp_3_cfg_l,
  input  [1:0]  io_ptw_pmp_3_cfg_a,
  input         io_ptw_pmp_3_cfg_x,
                io_ptw_pmp_3_cfg_w,
                io_ptw_pmp_3_cfg_r,
  input  [29:0] io_ptw_pmp_3_addr,
  input  [31:0] io_ptw_pmp_3_mask,
  input         io_ptw_pmp_4_cfg_l,
  input  [1:0]  io_ptw_pmp_4_cfg_a,
  input         io_ptw_pmp_4_cfg_x,
                io_ptw_pmp_4_cfg_w,
                io_ptw_pmp_4_cfg_r,
  input  [29:0] io_ptw_pmp_4_addr,
  input  [31:0] io_ptw_pmp_4_mask,
  input         io_ptw_pmp_5_cfg_l,
  input  [1:0]  io_ptw_pmp_5_cfg_a,
  input         io_ptw_pmp_5_cfg_x,
                io_ptw_pmp_5_cfg_w,
                io_ptw_pmp_5_cfg_r,
  input  [29:0] io_ptw_pmp_5_addr,
  input  [31:0] io_ptw_pmp_5_mask,
  input         io_ptw_pmp_6_cfg_l,
  input  [1:0]  io_ptw_pmp_6_cfg_a,
  input         io_ptw_pmp_6_cfg_x,
                io_ptw_pmp_6_cfg_w,
                io_ptw_pmp_6_cfg_r,
  input  [29:0] io_ptw_pmp_6_addr,
  input  [31:0] io_ptw_pmp_6_mask,
  input         io_ptw_pmp_7_cfg_l,
  input  [1:0]  io_ptw_pmp_7_cfg_a,
  input         io_ptw_pmp_7_cfg_x,
                io_ptw_pmp_7_cfg_w,
                io_ptw_pmp_7_cfg_r,
  input  [29:0] io_ptw_pmp_7_addr,
  input  [31:0] io_ptw_pmp_7_mask,
  input         io_kill,
  output        io_resp_miss,
  output [31:0] io_resp_paddr,
  output        io_resp_pf_inst,
                io_resp_ae_inst,
                io_resp_cacheable,
                io_ptw_req_valid,
                io_ptw_req_bits_valid,
  output [26:0] io_ptw_req_bits_bits_addr,
  output        io_ptw_req_bits_bits_need_gpa,
                io_ptw_req_bits_bits_vstage1,
                io_ptw_req_bits_bits_stage2
);

  wire [19:0]      _entries_barrier_5_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_4_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_3_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_2_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_1_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_c;	// @[package.scala:259:25]
  wire             _pmp_io_r;	// @[TLB.scala:403:19]
  wire             _pmp_io_w;	// @[TLB.scala:403:19]
  wire             _pmp_io_x;	// @[TLB.scala:403:19]
  wire [19:0]      _mpu_ppn_barrier_io_y_ppn;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_u;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_ae_final;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pf;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_gf;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_sw;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_sx;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_sr;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pw;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_px;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pr;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_ppp;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pal;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_paa;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_eff;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_c;	// @[package.scala:259:25]
  reg  [26:0]      sectored_entries_0_0_tag_vpn;	// @[TLB.scala:326:29]
  reg              sectored_entries_0_0_tag_v;	// @[TLB.scala:326:29]
  reg  [40:0]      sectored_entries_0_0_data_0;	// @[TLB.scala:326:29]
  reg  [40:0]      sectored_entries_0_0_data_1;	// @[TLB.scala:326:29]
  reg  [40:0]      sectored_entries_0_0_data_2;	// @[TLB.scala:326:29]
  reg  [40:0]      sectored_entries_0_0_data_3;	// @[TLB.scala:326:29]
  reg              sectored_entries_0_0_valid_0;	// @[TLB.scala:326:29]
  reg              sectored_entries_0_0_valid_1;	// @[TLB.scala:326:29]
  reg              sectored_entries_0_0_valid_2;	// @[TLB.scala:326:29]
  reg              sectored_entries_0_0_valid_3;	// @[TLB.scala:326:29]
  reg  [1:0]       superpage_entries_0_level;	// @[TLB.scala:328:30]
  reg  [26:0]      superpage_entries_0_tag_vpn;	// @[TLB.scala:328:30]
  reg              superpage_entries_0_tag_v;	// @[TLB.scala:328:30]
  reg  [40:0]      superpage_entries_0_data_0;	// @[TLB.scala:328:30]
  reg              superpage_entries_0_valid_0;	// @[TLB.scala:328:30]
  reg  [1:0]       superpage_entries_1_level;	// @[TLB.scala:328:30]
  reg  [26:0]      superpage_entries_1_tag_vpn;	// @[TLB.scala:328:30]
  reg              superpage_entries_1_tag_v;	// @[TLB.scala:328:30]
  reg  [40:0]      superpage_entries_1_data_0;	// @[TLB.scala:328:30]
  reg              superpage_entries_1_valid_0;	// @[TLB.scala:328:30]
  reg  [1:0]       superpage_entries_2_level;	// @[TLB.scala:328:30]
  reg  [26:0]      superpage_entries_2_tag_vpn;	// @[TLB.scala:328:30]
  reg              superpage_entries_2_tag_v;	// @[TLB.scala:328:30]
  reg  [40:0]      superpage_entries_2_data_0;	// @[TLB.scala:328:30]
  reg              superpage_entries_2_valid_0;	// @[TLB.scala:328:30]
  reg  [1:0]       superpage_entries_3_level;	// @[TLB.scala:328:30]
  reg  [26:0]      superpage_entries_3_tag_vpn;	// @[TLB.scala:328:30]
  reg              superpage_entries_3_tag_v;	// @[TLB.scala:328:30]
  reg  [40:0]      superpage_entries_3_data_0;	// @[TLB.scala:328:30]
  reg              superpage_entries_3_valid_0;	// @[TLB.scala:328:30]
  reg  [1:0]       special_entry_level;	// @[TLB.scala:333:56]
  reg  [26:0]      special_entry_tag_vpn;	// @[TLB.scala:333:56]
  reg              special_entry_tag_v;	// @[TLB.scala:333:56]
  reg  [40:0]      special_entry_data_0;	// @[TLB.scala:333:56]
  reg              special_entry_valid_0;	// @[TLB.scala:333:56]
  reg  [1:0]       state;	// @[TLB.scala:339:22]
  reg  [26:0]      r_refill_tag;	// @[TLB.scala:341:25]
  reg  [1:0]       r_superpage_repl_addr;	// @[TLB.scala:342:34]
  reg              r_sectored_hit_valid;	// @[TLB.scala:344:27]
  reg              r_vstage1_en;	// @[TLB.scala:346:25]
  reg              r_stage2_en;	// @[TLB.scala:347:24]
  reg              r_need_gpa;	// @[TLB.scala:348:23]
  wire             _vm_enabled_T_1 = io_ptw_ptbr_mode[3] & ~(io_req_bits_prv[1]);	// @[TLB.scala:359:27, :361:41, :386:45]
  wire             _T_22 = state == 2'h1;	// @[TLB.scala:339:22, package.scala:16:47]
  wire             mpu_ppn_ignore = special_entry_level == 2'h0;	// @[TLB.scala:186:28, :333:56]
  wire [8:0]       _GEN = mpu_ppn_ignore ? io_req_bits_vaddr[29:21] : 9'h0;	// @[TLB.scala:172:79, :186:28, :187:28, :322:30]
  wire [8:0]       _GEN_0 = special_entry_level[1] ? 9'h0 : io_req_bits_vaddr[20:12];	// @[TLB.scala:172:79, :186:28, :187:28, :322:30, :333:56]
  wire [27:0]      mpu_ppn = io_ptw_resp_valid ? {8'h0, io_ptw_resp_bits_pte_ppn[19:0]} : _vm_enabled_T_1 ? {8'h0, _mpu_ppn_barrier_io_y_ppn[19:18], _GEN | _mpu_ppn_barrier_io_y_ppn[17:9], _GEN_0 | _mpu_ppn_barrier_io_y_ppn[8:0]} : io_req_bits_vaddr[39:12];	// @[TLB.scala:184:26, :187:{28,47}, :386:45, :393:44, :399:20, :400:{20,146}, package.scala:259:25]
  wire [2:0]       mpu_priv = io_ptw_resp_valid ? 3'h1 : {io_ptw_status_debug, io_req_bits_prv};	// @[Cat.scala:33:92, TLB.scala:402:27]
  wire [1:0]       _GEN_1 = mpu_ppn[19:18] ^ 2'h1;	// @[Parameters.scala:137:31, TLB.scala:399:20, package.scala:16:47]
  wire             legal_address = mpu_ppn == 28'h3 | mpu_ppn == 28'h4 | mpu_ppn == 28'h60004 | mpu_ppn == 28'h64000 | mpu_ppn == 28'h64003 | mpu_ppn == 28'h64001 | mpu_ppn == 28'h64002 | mpu_ppn[27:14] == 14'h3 | mpu_ppn[27:4] == 24'h200 | mpu_ppn == 28'h40000 | mpu_ppn == 28'h0 | mpu_ppn == 28'h40001 | mpu_ppn == 28'h40002 | mpu_ppn == 28'h40003 | mpu_ppn[27:4] == 24'h1 | mpu_ppn == 28'h100 | mpu_ppn == 28'h110 | mpu_ppn[27:6] == 22'h1C00 | mpu_ppn[27:2] == 26'h20000;	// @[Cat.scala:33:92, Parameters.scala:137:{31,65}, TLB.scala:399:20, :410:67]
  wire             newEntry_c = legal_address & mpu_ppn[16];	// @[Cat.scala:33:92, TLB.scala:399:20, :410:67, :413:19]
  wire             deny_access_to_debug = ~(mpu_priv[2]) & mpu_ppn == 28'h0;	// @[Parameters.scala:137:65, TLB.scala:399:20, :402:27, :418:{39,50}]
  wire [17:0]      _GEN_2 = mpu_ppn[18:1] ^ 18'h20002;	// @[Cat.scala:33:92, Parameters.scala:137:31, TLB.scala:399:20]
  wire             newEntry_px = legal_address & ({mpu_ppn[14:13], mpu_ppn[8], mpu_ppn[4], mpu_ppn[2]} == 5'h0 | {mpu_ppn[18], mpu_ppn[14:13], mpu_ppn[8], ~(mpu_ppn[4])} == 5'h0 | {_GEN_1[0], mpu_ppn[14:13], mpu_ppn[8]} == 4'h0 | {_GEN_2[17], mpu_ppn[14:13], mpu_ppn[8], mpu_ppn[4], _GEN_2[1:0]} == 7'h0) & ~deny_access_to_debug & _pmp_io_x;	// @[Cat.scala:33:92, Parameters.scala:137:{31,45,65}, :616:89, TLB.scala:187:47, :399:20, :403:19, :410:67, :418:50, :419:44, :424:65]
  wire [24:0]      _sector_hits_T_4 = sectored_entries_0_0_tag_vpn[26:2] ^ io_req_bits_vaddr[38:14];	// @[TLB.scala:163:61, :322:30, :326:29]
  wire [17:0]      _GEN_3 = superpage_entries_0_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:172:52, :322:30, :328:30]
  wire             superpage_hits_ignore_1 = superpage_entries_0_level == 2'h0;	// @[TLB.scala:171:28, :328:30]
  wire [17:0]      _GEN_4 = superpage_entries_1_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:172:52, :322:30, :328:30]
  wire             superpage_hits_ignore_4 = superpage_entries_1_level == 2'h0;	// @[TLB.scala:171:28, :328:30]
  wire [17:0]      _GEN_5 = superpage_entries_2_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:172:52, :322:30, :328:30]
  wire             superpage_hits_ignore_7 = superpage_entries_2_level == 2'h0;	// @[TLB.scala:171:28, :328:30]
  wire [17:0]      _GEN_6 = superpage_entries_3_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:172:52, :322:30, :328:30]
  wire             superpage_hits_ignore_10 = superpage_entries_3_level == 2'h0;	// @[TLB.scala:171:28, :328:30]
  wire [3:0]       _GEN_7 = {{sectored_entries_0_0_valid_3}, {sectored_entries_0_0_valid_2}, {sectored_entries_0_0_valid_1}, {sectored_entries_0_0_valid_0}};	// @[TLB.scala:177:18, :326:29]
  wire             hitsVec_0 = _vm_enabled_T_1 & _GEN_7[io_req_bits_vaddr[13:12]] & _sector_hits_T_4 == 25'h0 & ~sectored_entries_0_0_tag_v;	// @[TLB.scala:163:{61,86,105}, :177:18, :322:30, :326:29, :386:45, :430:44, package.scala:155:13]
  wire             hitsVec_1 = _vm_enabled_T_1 & superpage_entries_0_valid_0 & ~superpage_entries_0_tag_v & _GEN_3[17:9] == 9'h0 & (superpage_hits_ignore_1 | _GEN_3[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{40,52,58,79}, :328:30, :386:45, :430:44]
  wire             hitsVec_2 = _vm_enabled_T_1 & superpage_entries_1_valid_0 & ~superpage_entries_1_tag_v & _GEN_4[17:9] == 9'h0 & (superpage_hits_ignore_4 | _GEN_4[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{40,52,58,79}, :328:30, :386:45, :430:44]
  wire             hitsVec_3 = _vm_enabled_T_1 & superpage_entries_2_valid_0 & ~superpage_entries_2_tag_v & _GEN_5[17:9] == 9'h0 & (superpage_hits_ignore_7 | _GEN_5[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{40,52,58,79}, :328:30, :386:45, :430:44]
  wire             hitsVec_4 = _vm_enabled_T_1 & superpage_entries_3_valid_0 & ~superpage_entries_3_tag_v & _GEN_6[17:9] == 9'h0 & (superpage_hits_ignore_10 | _GEN_6[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{40,52,58,79}, :328:30, :386:45, :430:44]
  wire [26:0]      _T_834 = special_entry_tag_vpn ^ io_req_bits_vaddr[38:12];	// @[TLB.scala:172:52, :322:30, :333:56]
  wire             hitsVec_5 = _vm_enabled_T_1 & special_entry_valid_0 & ~special_entry_tag_v & _T_834[26:18] == 9'h0 & (mpu_ppn_ignore | _T_834[17:9] == 9'h0) & (~(special_entry_level[1]) | _T_834[8:0] == 9'h0);	// @[TLB.scala:167:43, :172:{40,52,58,79}, :186:28, :333:56, :386:45, :430:44]
  wire [5:0]       real_hits = {hitsVec_5, hitsVec_4, hitsVec_3, hitsVec_2, hitsVec_1, hitsVec_0};	// @[Cat.scala:33:92, TLB.scala:430:44]
  wire [6:0]       hits = {~_vm_enabled_T_1, hitsVec_5, hitsVec_4, hitsVec_3, hitsVec_2, hitsVec_1, hitsVec_0};	// @[Cat.scala:33:92, TLB.scala:386:45, :430:44, :432:18]
  wire [3:0][40:0] _GEN_8 = {{sectored_entries_0_0_data_3}, {sectored_entries_0_0_data_2}, {sectored_entries_0_0_data_1}, {sectored_entries_0_0_data_0}};	// @[TLB.scala:159:77, :326:29]
  wire [40:0]      _entries_WIRE_1 = _GEN_8[io_req_bits_vaddr[13:12]];	// @[TLB.scala:159:77, :322:30, package.scala:155:13]
  wire             bad_va = _vm_enabled_T_1 & io_ptw_ptbr_mode[3] & ~(io_req_bits_vaddr[39:38] == 2'h0 | (&(io_req_bits_vaddr[39:38])));	// @[TLB.scala:361:41, :386:45, :548:43, :549:{37,51,59,86}, :557:34]
  wire             tlb_miss = _vm_enabled_T_1 & ~bad_va & real_hits == 6'h0;	// @[Cat.scala:33:92, TLB.scala:386:45, :557:34, :599:43, :600:40, :602:{56,64}]
  reg  [2:0]       state_reg_1;	// @[Replacement.scala:168:70]
  wire             multipleHits_rightOne_1 = hitsVec_1 | hitsVec_2;	// @[Misc.scala:182:16, TLB.scala:430:44]
  wire             multipleHits_rightOne_3 = hitsVec_4 | hitsVec_5;	// @[Misc.scala:182:16, TLB.scala:430:44]
  wire             multipleHits = hitsVec_1 & hitsVec_2 | hitsVec_0 & multipleHits_rightOne_1 | hitsVec_4 & hitsVec_5 | hitsVec_3 & multipleHits_rightOne_3 | (hitsVec_0 | multipleHits_rightOne_1) & (hitsVec_3 | multipleHits_rightOne_3);	// @[Misc.scala:182:{16,49,61}, TLB.scala:430:44]
  wire [2:0]       _GEN_9 = ~{superpage_entries_2_valid_0, superpage_entries_1_valid_0, superpage_entries_0_valid_0};	// @[Cat.scala:33:92, TLB.scala:328:30, :744:43]
  wire             superpage_hits_1 = superpage_entries_1_valid_0 & ~superpage_entries_1_tag_v & _GEN_4[17:9] == 9'h0 & (superpage_hits_ignore_4 | _GEN_4[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire             superpage_hits_2 = superpage_entries_2_valid_0 & ~superpage_entries_2_tag_v & _GEN_5[17:9] == 9'h0 & (superpage_hits_ignore_7 | _GEN_5[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire             superpage_hits_3 = superpage_entries_3_valid_0 & ~superpage_entries_3_tag_v & _GEN_6[17:9] == 9'h0 & (superpage_hits_ignore_10 | _GEN_6[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire [1:0]       hi_1 = {superpage_hits_3, superpage_hits_2};	// @[OneHot.scala:30:18, TLB.scala:172:29]
  wire             _T_16 = superpage_hits_3 | superpage_hits_1;	// @[OneHot.scala:32:28, TLB.scala:172:29]
  wire             invalidate_refill = _T_22 | (&state) | io_sfence_valid;	// @[TLB.scala:339:22, :397:88, package.scala:16:47]
  wire             newEntry_pr = legal_address & ~deny_access_to_debug & _pmp_io_r;	// @[TLB.scala:403:19, :410:67, :418:50, :419:{44,66}]
  wire [3:0]       _GEN_10 = {mpu_ppn[18], mpu_ppn[14], mpu_ppn[8], mpu_ppn[4]};	// @[Cat.scala:33:92, Parameters.scala:137:45, TLB.scala:399:20]
  wire [2:0]       _GEN_11 = {mpu_ppn[18], mpu_ppn[14], ~(mpu_ppn[8])};	// @[Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire [1:0]       _GEN_12 = {mpu_ppn[18], ~(mpu_ppn[14])};	// @[Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire [2:0]       _GEN_13 = {_GEN_1[0], mpu_ppn[8], mpu_ppn[4]};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire [2:0]       _GEN_14 = {_GEN_1[0], mpu_ppn[14], mpu_ppn[8]};	// @[Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire             newEntry_pw = legal_address & (_GEN_10 == 4'h0 | _GEN_11 == 3'h0 | _GEN_12 == 2'h0 | _GEN_13 == 3'h0 | _GEN_14 == 3'h0) & ~deny_access_to_debug & _pmp_io_w;	// @[Parameters.scala:137:{45,65}, :616:89, Replacement.scala:168:70, TLB.scala:403:19, :410:67, :418:50, :419:44, :420:70]
  wire             newEntry_ppp = legal_address & (_GEN_10 == 4'h0 | _GEN_11 == 3'h0 | _GEN_12 == 2'h0 | _GEN_13 == 3'h0 | _GEN_14 == 3'h0);	// @[Parameters.scala:137:{45,65}, :616:89, Replacement.scala:168:70, TLB.scala:410:67, :413:19]
  wire [5:0]       _GEN_15 = {mpu_ppn[19:18], mpu_ppn[16], mpu_ppn[14], mpu_ppn[8], mpu_ppn[4]};	// @[Cat.scala:33:92, Parameters.scala:137:45, TLB.scala:399:20]
  wire [6:0]       _GEN_16 = {mpu_ppn[19:18], mpu_ppn[16], mpu_ppn[14], mpu_ppn[8], mpu_ppn[4], mpu_ppn[2]};	// @[Cat.scala:33:92, Parameters.scala:137:45, TLB.scala:399:20]
  wire [6:0]       _GEN_17 = {mpu_ppn[19], mpu_ppn[16], mpu_ppn[14], mpu_ppn[8], mpu_ppn[4], mpu_ppn[2:1] ^ 2'h2};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire [6:0]       _GEN_18 = {mpu_ppn[19:18], mpu_ppn[16], mpu_ppn[14], ~(mpu_ppn[8]), mpu_ppn[2:1]};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire [3:0]       _GEN_19 = {mpu_ppn[19:18], mpu_ppn[16], ~(mpu_ppn[14])};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire [5:0]       _GEN_20 = {_GEN_1, mpu_ppn[16], mpu_ppn[8], mpu_ppn[4], mpu_ppn[2]};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:399:20]
  wire             newEntry_pal = legal_address & (_GEN_15 == 6'h0 | _GEN_16 == 7'h0 | _GEN_17 == 7'h0 | _GEN_18 == 7'h0 | _GEN_19 == 4'h0 | _GEN_20 == 6'h0);	// @[Parameters.scala:137:{45,65}, :616:89, TLB.scala:187:47, :410:67, :413:19, :599:43]
  wire             newEntry_paa = legal_address & (_GEN_15 == 6'h0 | _GEN_16 == 7'h0 | _GEN_17 == 7'h0 | _GEN_18 == 7'h0 | _GEN_19 == 4'h0 | _GEN_20 == 6'h0);	// @[Parameters.scala:137:{45,65}, :616:89, TLB.scala:187:47, :410:67, :413:19, :599:43]
  wire [6:0]       _GEN_21 = mpu_ppn[19:13] ^ 7'h22;	// @[Cat.scala:33:92, Parameters.scala:137:31, TLB.scala:399:20]
  wire             newEntry_eff = legal_address & ({mpu_ppn[19:18], mpu_ppn[14:13], mpu_ppn[8], mpu_ppn[4], mpu_ppn[1]} == 7'h0 | {mpu_ppn[19:18], mpu_ppn[14:13], ~(mpu_ppn[8]), mpu_ppn[2:1]} == 7'h0 | {mpu_ppn[19:18], mpu_ppn[14:13] ^ 2'h1, mpu_ppn[8], mpu_ppn[4]} == 6'h0 | {mpu_ppn[19:18], ~(mpu_ppn[14])} == 3'h0 | {_GEN_21[6:5], _GEN_21[1:0], mpu_ppn[8], mpu_ppn[4], mpu_ppn[2]} == 7'h0);	// @[Cat.scala:33:92, Parameters.scala:137:{31,45,65}, :616:89, Replacement.scala:168:70, TLB.scala:187:47, :399:20, :410:67, :413:19, :599:43, package.scala:16:47]
  wire             refill_v = r_vstage1_en | r_stage2_en;	// @[TLB.scala:346:25, :347:24, :438:33]
  wire             newEntry_g = io_ptw_resp_bits_pte_g & io_ptw_resp_bits_pte_v;	// @[TLB.scala:443:25]
  wire             newEntry_sr = io_ptw_resp_bits_pte_v & (io_ptw_resp_bits_pte_r | io_ptw_resp_bits_pte_x & ~io_ptw_resp_bits_pte_w) & io_ptw_resp_bits_pte_a & io_ptw_resp_bits_pte_r;	// @[PTW.scala:141:{38,44,47}, :149:35]
  wire             newEntry_sw = io_ptw_resp_bits_pte_v & (io_ptw_resp_bits_pte_r | io_ptw_resp_bits_pte_x & ~io_ptw_resp_bits_pte_w) & io_ptw_resp_bits_pte_a & io_ptw_resp_bits_pte_w & io_ptw_resp_bits_pte_d;	// @[PTW.scala:141:{38,44,47}, :151:40]
  wire             newEntry_sx = io_ptw_resp_bits_pte_v & (io_ptw_resp_bits_pte_r | io_ptw_resp_bits_pte_x & ~io_ptw_resp_bits_pte_w) & io_ptw_resp_bits_pte_a & io_ptw_resp_bits_pte_x;	// @[PTW.scala:141:{38,44,47}, :153:35]
  wire             _GEN_22 = io_ptw_resp_valid & ~io_ptw_resp_bits_homogeneous;	// @[TLB.scala:200:18, :333:56, :436:20, :463:{39,70}]
  wire             _GEN_23 = _GEN_22 | special_entry_valid_0;	// @[TLB.scala:200:18, :205:16, :333:56, :436:20, :463:70]
  wire             _GEN_24 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & r_superpage_repl_addr == 2'h0;	// @[TLB.scala:328:30, :342:34, :436:20, :463:70, :465:40, :467:82]
  wire             _GEN_25 = _GEN_24 ? ~invalidate_refill : superpage_entries_0_valid_0;	// @[TLB.scala:205:16, :209:46, :328:30, :397:88, :436:20, :463:70, :469:34]
  wire             _GEN_26 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & r_superpage_repl_addr == 2'h1;	// @[TLB.scala:328:30, :342:34, :436:20, :463:70, :465:40, :467:82, package.scala:16:47]
  wire             _GEN_27 = _GEN_26 ? ~invalidate_refill : superpage_entries_1_valid_0;	// @[TLB.scala:205:16, :209:46, :328:30, :397:88, :436:20, :463:70, :469:34]
  wire             _GEN_28 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & r_superpage_repl_addr == 2'h2;	// @[TLB.scala:328:30, :342:34, :436:20, :463:70, :465:40, :467:82]
  wire             _GEN_29 = _GEN_28 ? ~invalidate_refill : superpage_entries_2_valid_0;	// @[TLB.scala:205:16, :209:46, :328:30, :397:88, :436:20, :463:70, :469:34]
  wire             _GEN_30 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & (&r_superpage_repl_addr);	// @[TLB.scala:328:30, :342:34, :436:20, :463:70, :465:40, :467:82]
  wire             _GEN_31 = _GEN_30 ? ~invalidate_refill : superpage_entries_3_valid_0;	// @[TLB.scala:205:16, :209:46, :328:30, :397:88, :436:20, :463:70, :469:34]
  wire             _GEN_32 = ~io_ptw_resp_bits_homogeneous | ~(io_ptw_resp_bits_level[1]);	// @[TLB.scala:326:29, :463:{39,70}, :465:{40,58}, :475:84]
  wire             _GEN_33 = ~io_ptw_resp_valid | _GEN_32;	// @[TLB.scala:326:29, :436:20, :463:70, :465:58, :475:84]
  wire             _GEN_34 = r_refill_tag[1:0] == 2'h0;	// @[TLB.scala:205:16, :341:25, package.scala:155:13]
  wire             _GEN_35 = r_refill_tag[1:0] == 2'h1;	// @[TLB.scala:205:16, :341:25, package.scala:16:47, :155:13]
  wire             _GEN_36 = r_refill_tag[1:0] == 2'h2;	// @[TLB.scala:205:16, :341:25, package.scala:155:13]
  wire [40:0]      _sectored_entries_0_0_data_T = {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:206:24, :413:19, :419:66, :420:70, :424:65, :440:18, :443:25]
  wire             _GEN_37 = _GEN_33 ? sectored_entries_0_0_valid_0 : ~invalidate_refill & (_GEN_34 | r_sectored_hit_valid & sectored_entries_0_0_valid_0);	// @[TLB.scala:205:16, :209:46, :326:29, :344:27, :397:88, :436:20, :463:70, :469:34, :476:38, :478:34]
  wire             _GEN_38 = _GEN_33 ? sectored_entries_0_0_valid_1 : ~invalidate_refill & (_GEN_35 | r_sectored_hit_valid & sectored_entries_0_0_valid_1);	// @[TLB.scala:205:16, :209:46, :326:29, :344:27, :397:88, :436:20, :463:70, :469:34, :476:38, :478:34]
  wire             _GEN_39 = _GEN_33 ? sectored_entries_0_0_valid_2 : ~invalidate_refill & (_GEN_36 | r_sectored_hit_valid & sectored_entries_0_0_valid_2);	// @[TLB.scala:205:16, :209:46, :326:29, :344:27, :397:88, :436:20, :463:70, :469:34, :476:38, :478:34]
  wire             _GEN_40 = _GEN_33 ? sectored_entries_0_0_valid_3 : ~invalidate_refill & ((&(r_refill_tag[1:0])) | r_sectored_hit_valid & sectored_entries_0_0_valid_3);	// @[TLB.scala:205:16, :209:46, :326:29, :341:25, :344:27, :397:88, :436:20, :463:70, :469:34, :476:38, :478:34, package.scala:155:13]
  wire             _T_21 = state == 2'h0 & io_req_valid & tlb_miss;	// @[TLB.scala:339:22, :602:64, :620:25, :666:23]
  wire [24:0]      _T_35 = sectored_entries_0_0_tag_vpn[26:2] ^ io_req_bits_vaddr[38:14];	// @[TLB.scala:163:61, :322:30, :326:29]
  wire             _T_38 = _T_35 == 25'h0 & ~sectored_entries_0_0_tag_v;	// @[TLB.scala:163:{61,86,95,105}, :326:29]
  wire             _GEN_41 = _T_38 & ~sectored_entries_0_0_tag_v & io_req_bits_vaddr[13:12] == 2'h0;	// @[TLB.scala:163:{95,105}, :218:43, :220:{42,62,66}, :322:30, :326:29, :436:20, package.scala:155:13]
  wire             _GEN_42 = _T_38 & ~sectored_entries_0_0_tag_v & io_req_bits_vaddr[13:12] == 2'h1;	// @[TLB.scala:163:{95,105}, :218:43, :220:{42,62,66}, :322:30, :326:29, :436:20, package.scala:16:47, :155:13]
  wire             _GEN_43 = _T_38 & ~sectored_entries_0_0_tag_v & io_req_bits_vaddr[13:12] == 2'h2;	// @[TLB.scala:163:{95,105}, :218:43, :220:{42,62,66}, :322:30, :326:29, :436:20, package.scala:155:13]
  wire             _GEN_44 = _T_38 & ~sectored_entries_0_0_tag_v & (&(io_req_bits_vaddr[13:12]));	// @[TLB.scala:163:{95,105}, :218:43, :220:{42,62,66}, :322:30, :326:29, :436:20, package.scala:155:13]
  wire             _T_145 = _T_35[24:16] == 9'h0;	// @[TLB.scala:163:61, :172:79, :225:{28,63}]
  wire             _T_453 = superpage_entries_0_valid_0 & ~superpage_entries_0_tag_v & _GEN_3[17:9] == 9'h0 & (superpage_hits_ignore_1 | _GEN_3[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire             _T_548 = superpage_entries_1_valid_0 & ~superpage_entries_1_tag_v & _GEN_4[17:9] == 9'h0 & (superpage_hits_ignore_4 | _GEN_4[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire             _T_643 = superpage_entries_2_valid_0 & ~superpage_entries_2_tag_v & _GEN_5[17:9] == 9'h0 & (superpage_hits_ignore_7 | _GEN_5[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire             _T_738 = superpage_entries_3_valid_0 & ~superpage_entries_3_tag_v & _GEN_6[17:9] == 9'h0 & (superpage_hits_ignore_10 | _GEN_6[8:0] == 9'h0);	// @[TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30]
  wire             _T_833 = special_entry_valid_0 & ~special_entry_tag_v & _T_834[26:18] == 9'h0 & (mpu_ppn_ignore | _T_834[17:9] == 9'h0) & (~(special_entry_level[1]) | _T_834[8:0] == 9'h0);	// @[TLB.scala:167:43, :172:{29,40,52,58,79}, :186:28, :333:56]
  wire             _T_1122 = multipleHits | reset;	// @[Misc.scala:182:49, TLB.scala:719:24]
  always @(posedge clock) begin
    if (_GEN_33) begin	// @[TLB.scala:326:29, :436:20, :463:70]
    end
    else begin	// @[TLB.scala:326:29, :436:20, :463:70]
      sectored_entries_0_0_tag_vpn <= r_refill_tag;	// @[TLB.scala:326:29, :341:25]
      sectored_entries_0_0_tag_v <= refill_v;	// @[TLB.scala:326:29, :438:33]
    end
    if (~io_ptw_resp_valid | _GEN_32 | ~_GEN_34) begin	// @[TLB.scala:205:16, :326:29, :436:20, :463:70, :465:58, :475:84]
    end
    else	// @[TLB.scala:326:29, :436:20, :463:70]
      sectored_entries_0_0_data_0 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:206:24, :326:29]
    if (~io_ptw_resp_valid | _GEN_32 | ~_GEN_35) begin	// @[TLB.scala:205:16, :326:29, :436:20, :463:70, :465:58, :475:84]
    end
    else	// @[TLB.scala:326:29, :436:20, :463:70]
      sectored_entries_0_0_data_1 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:206:24, :326:29]
    if (~io_ptw_resp_valid | _GEN_32 | ~_GEN_36) begin	// @[TLB.scala:205:16, :326:29, :436:20, :463:70, :465:58, :475:84]
    end
    else	// @[TLB.scala:326:29, :436:20, :463:70]
      sectored_entries_0_0_data_2 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:206:24, :326:29]
    if (~io_ptw_resp_valid | _GEN_32 | ~(&(r_refill_tag[1:0]))) begin	// @[TLB.scala:205:16, :326:29, :341:25, :436:20, :463:70, :465:58, :475:84, package.scala:155:13]
    end
    else	// @[TLB.scala:326:29, :436:20, :463:70]
      sectored_entries_0_0_data_3 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:206:24, :326:29]
    sectored_entries_0_0_valid_0 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_T_145 ? ~(~sectored_entries_0_0_tag_v & sectored_entries_0_0_data_0[0] | _GEN_41) & _GEN_37 : ~_GEN_41 & _GEN_37) : io_sfence_bits_rs2 ? ~(~sectored_entries_0_0_tag_v & ~(sectored_entries_0_0_data_0[19])) & _GEN_37 : sectored_entries_0_0_tag_v & _GEN_37) : _GEN_37);	// @[TLB.scala:155:39, :163:105, :209:46, :212:{32,36}, :218:43, :220:{62,66}, :225:{63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :326:29, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    sectored_entries_0_0_valid_1 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_T_145 ? ~(~sectored_entries_0_0_tag_v & sectored_entries_0_0_data_1[0] | _GEN_42) & _GEN_38 : ~_GEN_42 & _GEN_38) : io_sfence_bits_rs2 ? ~(~sectored_entries_0_0_tag_v & ~(sectored_entries_0_0_data_1[19])) & _GEN_38 : sectored_entries_0_0_tag_v & _GEN_38) : _GEN_38);	// @[TLB.scala:155:39, :163:105, :209:46, :212:{32,36}, :218:43, :220:{62,66}, :225:{63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :326:29, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    sectored_entries_0_0_valid_2 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_T_145 ? ~(~sectored_entries_0_0_tag_v & sectored_entries_0_0_data_2[0] | _GEN_43) & _GEN_39 : ~_GEN_43 & _GEN_39) : io_sfence_bits_rs2 ? ~(~sectored_entries_0_0_tag_v & ~(sectored_entries_0_0_data_2[19])) & _GEN_39 : sectored_entries_0_0_tag_v & _GEN_39) : _GEN_39);	// @[TLB.scala:155:39, :163:105, :209:46, :212:{32,36}, :218:43, :220:{62,66}, :225:{63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :326:29, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    sectored_entries_0_0_valid_3 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_T_145 ? ~(~sectored_entries_0_0_tag_v & sectored_entries_0_0_data_3[0] | _GEN_44) & _GEN_40 : ~_GEN_44 & _GEN_40) : io_sfence_bits_rs2 ? ~(~sectored_entries_0_0_tag_v & ~(sectored_entries_0_0_data_3[19])) & _GEN_40 : sectored_entries_0_0_tag_v & _GEN_40) : _GEN_40);	// @[TLB.scala:155:39, :163:105, :209:46, :212:{32,36}, :218:43, :220:{62,66}, :225:{63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :326:29, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    if (_GEN_24) begin	// @[TLB.scala:328:30, :436:20, :463:70]
      superpage_entries_0_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:202:16, :328:30, package.scala:155:13]
      superpage_entries_0_tag_vpn <= r_refill_tag;	// @[TLB.scala:328:30, :341:25]
      superpage_entries_0_tag_v <= refill_v;	// @[TLB.scala:328:30, :438:33]
      superpage_entries_0_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:206:24, :328:30, :413:19, :419:66, :420:70, :424:65, :440:18, :443:25]
    end
    superpage_entries_0_valid_0 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_GEN_3[17:9] == 9'h0 ? ~(~superpage_entries_0_tag_v & superpage_entries_0_data_0[0] | _T_453) & _GEN_25 : ~_T_453 & _GEN_25) : io_sfence_bits_rs2 ? ~(~superpage_entries_0_tag_v & ~(superpage_entries_0_data_0[19])) & _GEN_25 : superpage_entries_0_tag_v & _GEN_25) : _GEN_25);	// @[TLB.scala:155:39, :167:43, :172:{29,52,79}, :209:46, :212:{32,36}, :216:32, :225:{28,63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :328:30, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    if (_GEN_26) begin	// @[TLB.scala:328:30, :436:20, :463:70]
      superpage_entries_1_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:202:16, :328:30, package.scala:155:13]
      superpage_entries_1_tag_vpn <= r_refill_tag;	// @[TLB.scala:328:30, :341:25]
      superpage_entries_1_tag_v <= refill_v;	// @[TLB.scala:328:30, :438:33]
      superpage_entries_1_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:206:24, :328:30, :413:19, :419:66, :420:70, :424:65, :440:18, :443:25]
    end
    superpage_entries_1_valid_0 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_GEN_4[17:9] == 9'h0 ? ~(~superpage_entries_1_tag_v & superpage_entries_1_data_0[0] | _T_548) & _GEN_27 : ~_T_548 & _GEN_27) : io_sfence_bits_rs2 ? ~(~superpage_entries_1_tag_v & ~(superpage_entries_1_data_0[19])) & _GEN_27 : superpage_entries_1_tag_v & _GEN_27) : _GEN_27);	// @[TLB.scala:155:39, :167:43, :172:{29,52,79}, :209:46, :212:{32,36}, :216:32, :225:{28,63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :328:30, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    if (_GEN_28) begin	// @[TLB.scala:328:30, :436:20, :463:70]
      superpage_entries_2_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:202:16, :328:30, package.scala:155:13]
      superpage_entries_2_tag_vpn <= r_refill_tag;	// @[TLB.scala:328:30, :341:25]
      superpage_entries_2_tag_v <= refill_v;	// @[TLB.scala:328:30, :438:33]
      superpage_entries_2_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:206:24, :328:30, :413:19, :419:66, :420:70, :424:65, :440:18, :443:25]
    end
    superpage_entries_2_valid_0 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_GEN_5[17:9] == 9'h0 ? ~(~superpage_entries_2_tag_v & superpage_entries_2_data_0[0] | _T_643) & _GEN_29 : ~_T_643 & _GEN_29) : io_sfence_bits_rs2 ? ~(~superpage_entries_2_tag_v & ~(superpage_entries_2_data_0[19])) & _GEN_29 : superpage_entries_2_tag_v & _GEN_29) : _GEN_29);	// @[TLB.scala:155:39, :167:43, :172:{29,52,79}, :209:46, :212:{32,36}, :216:32, :225:{28,63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :328:30, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    if (_GEN_30) begin	// @[TLB.scala:328:30, :436:20, :463:70]
      superpage_entries_3_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:202:16, :328:30, package.scala:155:13]
      superpage_entries_3_tag_vpn <= r_refill_tag;	// @[TLB.scala:328:30, :341:25]
      superpage_entries_3_tag_v <= refill_v;	// @[TLB.scala:328:30, :438:33]
      superpage_entries_3_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:206:24, :328:30, :413:19, :419:66, :420:70, :424:65, :440:18, :443:25]
    end
    superpage_entries_3_valid_0 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_GEN_6[17:9] == 9'h0 ? ~(~superpage_entries_3_tag_v & superpage_entries_3_data_0[0] | _T_738) & _GEN_31 : ~_T_738 & _GEN_31) : io_sfence_bits_rs2 ? ~(~superpage_entries_3_tag_v & ~(superpage_entries_3_data_0[19])) & _GEN_31 : superpage_entries_3_tag_v & _GEN_31) : _GEN_31);	// @[TLB.scala:155:39, :167:43, :172:{29,52,79}, :209:46, :212:{32,36}, :216:32, :225:{28,63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :328:30, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    if (_GEN_22) begin	// @[TLB.scala:200:18, :333:56, :436:20, :463:70]
      special_entry_level <= io_ptw_resp_bits_level;	// @[TLB.scala:333:56]
      special_entry_tag_vpn <= r_refill_tag;	// @[TLB.scala:333:56, :341:25]
      special_entry_tag_v <= refill_v;	// @[TLB.scala:333:56, :438:33]
      special_entry_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:206:24, :333:56, :413:19, :419:66, :420:70, :424:65, :440:18, :443:25]
    end
    special_entry_valid_0 <= ~_T_1122 & (io_sfence_valid ? (io_sfence_bits_rs1 ? (_T_834[26:18] == 9'h0 ? ~(~special_entry_tag_v & special_entry_data_0[0] | _T_833) & _GEN_23 : ~_T_833 & _GEN_23) : io_sfence_bits_rs2 ? ~(~special_entry_tag_v & ~(special_entry_data_0[19])) & _GEN_23 : special_entry_tag_v & _GEN_23) : _GEN_23);	// @[TLB.scala:155:39, :167:43, :172:{29,52,79}, :205:16, :209:46, :212:{32,36}, :216:32, :225:{28,63,72}, :227:{33,60,64}, :232:{19,31,34,40,44}, :333:56, :436:20, :463:70, :705:19, :710:42, :711:47, :715:46, :719:{24,41}]
    if (_T_21) begin	// @[TLB.scala:666:23]
      r_refill_tag <= io_req_bits_vaddr[38:12];	// @[TLB.scala:322:30, :341:25]
      if (&{superpage_entries_3_valid_0, superpage_entries_2_valid_0, superpage_entries_1_valid_0, superpage_entries_0_valid_0})	// @[Cat.scala:33:92, TLB.scala:328:30, :744:16]
        r_superpage_repl_addr <= {state_reg_1[2], state_reg_1[2] ? state_reg_1[1] : state_reg_1[0]};	// @[Cat.scala:33:92, Replacement.scala:168:70, :243:38, :245:38, :250:16, TLB.scala:342:34, package.scala:155:13]
      else if (_GEN_9[0])	// @[OneHot.scala:47:45, TLB.scala:744:43]
        r_superpage_repl_addr <= 2'h0;	// @[TLB.scala:342:34]
      else if (_GEN_9[1])	// @[OneHot.scala:47:45, TLB.scala:744:43]
        r_superpage_repl_addr <= 2'h1;	// @[TLB.scala:342:34, package.scala:16:47]
      else	// @[OneHot.scala:47:45]
        r_superpage_repl_addr <= {1'h1, ~(_GEN_9[2])};	// @[Mux.scala:47:70, OneHot.scala:47:45, TLB.scala:342:34, :744:43]
      r_sectored_hit_valid <= (sectored_entries_0_0_valid_0 | sectored_entries_0_0_valid_1 | sectored_entries_0_0_valid_2 | sectored_entries_0_0_valid_3) & _sector_hits_T_4 == 25'h0 & ~sectored_entries_0_0_tag_v;	// @[TLB.scala:161:55, :163:{61,86,105}, :326:29, :344:27, package.scala:73:59]
      r_need_gpa <= |real_hits;	// @[Cat.scala:33:92, TLB.scala:348:23, :599:43]
    end
    r_vstage1_en <= ~_T_21 & r_vstage1_en;	// @[TLB.scala:346:25, :666:{23,36}, :670:20]
    r_stage2_en <= ~_T_21 & r_stage2_en;	// @[TLB.scala:346:25, :347:24, :666:{23,36}, :670:20, :671:19]
    if (reset) begin
      state <= 2'h0;	// @[TLB.scala:339:22]
      state_reg_1 <= 3'h0;	// @[Replacement.scala:168:70]
    end
    else begin
      if (io_ptw_resp_valid)
        state <= 2'h0;	// @[TLB.scala:339:22]
      else if (state == 2'h2 & io_sfence_valid)	// @[TLB.scala:339:22, :696:{17,28}]
        state <= 2'h3;	// @[TLB.scala:339:22, package.scala:16:47]
      else if (_T_22) begin	// @[package.scala:16:47]
        if (io_kill)
          state <= 2'h0;	// @[TLB.scala:339:22]
        else if (io_ptw_req_ready)
          state <= {1'h1, io_sfence_valid};	// @[TLB.scala:339:22, :691:45]
        else if (io_sfence_valid)
          state <= 2'h0;	// @[TLB.scala:339:22]
        else if (_T_21)	// @[TLB.scala:666:23]
          state <= 2'h1;	// @[TLB.scala:339:22, package.scala:16:47]
      end
      else if (_T_21)	// @[TLB.scala:666:23]
        state <= 2'h1;	// @[TLB.scala:339:22, package.scala:16:47]
      if (io_req_valid & _vm_enabled_T_1 & (superpage_entries_0_valid_0 & ~superpage_entries_0_tag_v & _GEN_3[17:9] == 9'h0 & (superpage_hits_ignore_1 | _GEN_3[8:0] == 9'h0) | superpage_hits_1 | superpage_hits_2 | superpage_hits_3))	// @[Replacement.scala:168:70, :172:15, TLB.scala:167:43, :171:28, :172:{29,40,52,58,79}, :328:30, :386:45, :606:37, :609:31, package.scala:73:59]
        state_reg_1 <= {~(|hi_1), (|hi_1) ? ~_T_16 : state_reg_1[1], (|hi_1) ? state_reg_1[0] : ~_T_16};	// @[Cat.scala:33:92, OneHot.scala:30:18, :32:{14,28}, Replacement.scala:168:70, :196:33, :198:38, :203:16, :206:16, :218:7, package.scala:155:13]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[TLB.scala:706:13]
      if (io_sfence_valid & ~reset & ~(~io_sfence_bits_rs1 | io_sfence_bits_addr[38:12] == io_req_bits_vaddr[38:12])) begin	// @[TLB.scala:322:30, :706:{13,14,34,58,72}]
        if (`ASSERT_VERBOSE_COND_)	// @[TLB.scala:706:13]
          $error("Assertion failed\n    at TLB.scala:706 assert(!io.sfence.bits.rs1 || (io.sfence.bits.addr >> pgIdxBits) === vpn)\n");	// @[TLB.scala:706:13]
        if (`STOP_COND_)	// @[TLB.scala:706:13]
          $fatal;	// @[TLB.scala:706:13]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        sectored_entries_0_0_tag_vpn = _RANDOM_0[28:2];	// @[TLB.scala:326:29]
        sectored_entries_0_0_tag_v = _RANDOM_0[29];	// @[TLB.scala:326:29]
        sectored_entries_0_0_data_0 = {_RANDOM_0[31:30], _RANDOM_1, _RANDOM_2[6:0]};	// @[TLB.scala:326:29]
        sectored_entries_0_0_data_1 = {_RANDOM_2[31:7], _RANDOM_3[15:0]};	// @[TLB.scala:326:29]
        sectored_entries_0_0_data_2 = {_RANDOM_3[31:16], _RANDOM_4[24:0]};	// @[TLB.scala:326:29]
        sectored_entries_0_0_data_3 = {_RANDOM_4[31:25], _RANDOM_5, _RANDOM_6[1:0]};	// @[TLB.scala:326:29]
        sectored_entries_0_0_valid_0 = _RANDOM_6[2];	// @[TLB.scala:326:29]
        sectored_entries_0_0_valid_1 = _RANDOM_6[3];	// @[TLB.scala:326:29]
        sectored_entries_0_0_valid_2 = _RANDOM_6[4];	// @[TLB.scala:326:29]
        sectored_entries_0_0_valid_3 = _RANDOM_6[5];	// @[TLB.scala:326:29]
        superpage_entries_0_level = _RANDOM_6[7:6];	// @[TLB.scala:326:29, :328:30]
        superpage_entries_0_tag_vpn = {_RANDOM_6[31:8], _RANDOM_7[2:0]};	// @[TLB.scala:326:29, :328:30]
        superpage_entries_0_tag_v = _RANDOM_7[3];	// @[TLB.scala:328:30]
        superpage_entries_0_data_0 = {_RANDOM_7[31:4], _RANDOM_8[12:0]};	// @[TLB.scala:328:30]
        superpage_entries_0_valid_0 = _RANDOM_8[13];	// @[TLB.scala:328:30]
        superpage_entries_1_level = _RANDOM_8[15:14];	// @[TLB.scala:328:30]
        superpage_entries_1_tag_vpn = {_RANDOM_8[31:16], _RANDOM_9[10:0]};	// @[TLB.scala:328:30]
        superpage_entries_1_tag_v = _RANDOM_9[11];	// @[TLB.scala:328:30]
        superpage_entries_1_data_0 = {_RANDOM_9[31:12], _RANDOM_10[20:0]};	// @[TLB.scala:328:30]
        superpage_entries_1_valid_0 = _RANDOM_10[21];	// @[TLB.scala:328:30]
        superpage_entries_2_level = _RANDOM_10[23:22];	// @[TLB.scala:328:30]
        superpage_entries_2_tag_vpn = {_RANDOM_10[31:24], _RANDOM_11[18:0]};	// @[TLB.scala:328:30]
        superpage_entries_2_tag_v = _RANDOM_11[19];	// @[TLB.scala:328:30]
        superpage_entries_2_data_0 = {_RANDOM_11[31:20], _RANDOM_12[28:0]};	// @[TLB.scala:328:30]
        superpage_entries_2_valid_0 = _RANDOM_12[29];	// @[TLB.scala:328:30]
        superpage_entries_3_level = _RANDOM_12[31:30];	// @[TLB.scala:328:30]
        superpage_entries_3_tag_vpn = _RANDOM_13[26:0];	// @[TLB.scala:328:30]
        superpage_entries_3_tag_v = _RANDOM_13[27];	// @[TLB.scala:328:30]
        superpage_entries_3_data_0 = {_RANDOM_13[31:28], _RANDOM_14, _RANDOM_15[4:0]};	// @[TLB.scala:328:30]
        superpage_entries_3_valid_0 = _RANDOM_15[5];	// @[TLB.scala:328:30]
        special_entry_level = _RANDOM_15[7:6];	// @[TLB.scala:328:30, :333:56]
        special_entry_tag_vpn = {_RANDOM_15[31:8], _RANDOM_16[2:0]};	// @[TLB.scala:328:30, :333:56]
        special_entry_tag_v = _RANDOM_16[3];	// @[TLB.scala:333:56]
        special_entry_data_0 = {_RANDOM_16[31:4], _RANDOM_17[12:0]};	// @[TLB.scala:333:56]
        special_entry_valid_0 = _RANDOM_17[13];	// @[TLB.scala:333:56]
        state = _RANDOM_17[15:14];	// @[TLB.scala:333:56, :339:22]
        r_refill_tag = {_RANDOM_17[31:16], _RANDOM_18[10:0]};	// @[TLB.scala:333:56, :341:25]
        r_superpage_repl_addr = _RANDOM_18[12:11];	// @[TLB.scala:341:25, :342:34]
        r_sectored_hit_valid = _RANDOM_18[13];	// @[TLB.scala:341:25, :344:27]
        r_vstage1_en = _RANDOM_18[17];	// @[TLB.scala:341:25, :346:25]
        r_stage2_en = _RANDOM_18[18];	// @[TLB.scala:341:25, :347:24]
        r_need_gpa = _RANDOM_18[19];	// @[TLB.scala:341:25, :348:23]
        state_reg_1 = _RANDOM_20[27:25];	// @[Replacement.scala:168:70]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  OptimizationBarrier mpu_ppn_barrier (	// @[package.scala:259:25]
    .io_x_ppn      (special_entry_data_0[40:21]),	// @[TLB.scala:159:77, :333:56]
    .io_x_u        (special_entry_data_0[20]),	// @[TLB.scala:159:77, :333:56]
    .io_x_ae_ptw   (special_entry_data_0[18]),	// @[TLB.scala:159:77, :333:56]
    .io_x_ae_final (special_entry_data_0[17]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pf       (special_entry_data_0[16]),	// @[TLB.scala:159:77, :333:56]
    .io_x_gf       (special_entry_data_0[15]),	// @[TLB.scala:159:77, :333:56]
    .io_x_sw       (special_entry_data_0[14]),	// @[TLB.scala:159:77, :333:56]
    .io_x_sx       (special_entry_data_0[13]),	// @[TLB.scala:159:77, :333:56]
    .io_x_sr       (special_entry_data_0[12]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pw       (special_entry_data_0[8]),	// @[TLB.scala:159:77, :333:56]
    .io_x_px       (special_entry_data_0[7]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pr       (special_entry_data_0[6]),	// @[TLB.scala:159:77, :333:56]
    .io_x_ppp      (special_entry_data_0[5]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pal      (special_entry_data_0[4]),	// @[TLB.scala:159:77, :333:56]
    .io_x_paa      (special_entry_data_0[3]),	// @[TLB.scala:159:77, :333:56]
    .io_x_eff      (special_entry_data_0[2]),	// @[TLB.scala:159:77, :333:56]
    .io_x_c        (special_entry_data_0[1]),	// @[TLB.scala:159:77, :333:56]
    .io_y_ppn      (_mpu_ppn_barrier_io_y_ppn),
    .io_y_u        (_mpu_ppn_barrier_io_y_u),
    .io_y_ae_ptw   (_mpu_ppn_barrier_io_y_ae_ptw),
    .io_y_ae_final (_mpu_ppn_barrier_io_y_ae_final),
    .io_y_pf       (_mpu_ppn_barrier_io_y_pf),
    .io_y_gf       (_mpu_ppn_barrier_io_y_gf),
    .io_y_sw       (_mpu_ppn_barrier_io_y_sw),
    .io_y_sx       (_mpu_ppn_barrier_io_y_sx),
    .io_y_sr       (_mpu_ppn_barrier_io_y_sr),
    .io_y_pw       (_mpu_ppn_barrier_io_y_pw),
    .io_y_px       (_mpu_ppn_barrier_io_y_px),
    .io_y_pr       (_mpu_ppn_barrier_io_y_pr),
    .io_y_ppp      (_mpu_ppn_barrier_io_y_ppp),
    .io_y_pal      (_mpu_ppn_barrier_io_y_pal),
    .io_y_paa      (_mpu_ppn_barrier_io_y_paa),
    .io_y_eff      (_mpu_ppn_barrier_io_y_eff),
    .io_y_c        (_mpu_ppn_barrier_io_y_c)
  );
  PMPChecker_2 pmp (	// @[TLB.scala:403:19]
    .io_prv         (mpu_priv[1:0]),	// @[TLB.scala:402:27, :407:14]
    .io_pmp_0_cfg_l (io_ptw_pmp_0_cfg_l),
    .io_pmp_0_cfg_a (io_ptw_pmp_0_cfg_a),
    .io_pmp_0_cfg_x (io_ptw_pmp_0_cfg_x),
    .io_pmp_0_cfg_w (io_ptw_pmp_0_cfg_w),
    .io_pmp_0_cfg_r (io_ptw_pmp_0_cfg_r),
    .io_pmp_0_addr  (io_ptw_pmp_0_addr),
    .io_pmp_0_mask  (io_ptw_pmp_0_mask),
    .io_pmp_1_cfg_l (io_ptw_pmp_1_cfg_l),
    .io_pmp_1_cfg_a (io_ptw_pmp_1_cfg_a),
    .io_pmp_1_cfg_x (io_ptw_pmp_1_cfg_x),
    .io_pmp_1_cfg_w (io_ptw_pmp_1_cfg_w),
    .io_pmp_1_cfg_r (io_ptw_pmp_1_cfg_r),
    .io_pmp_1_addr  (io_ptw_pmp_1_addr),
    .io_pmp_1_mask  (io_ptw_pmp_1_mask),
    .io_pmp_2_cfg_l (io_ptw_pmp_2_cfg_l),
    .io_pmp_2_cfg_a (io_ptw_pmp_2_cfg_a),
    .io_pmp_2_cfg_x (io_ptw_pmp_2_cfg_x),
    .io_pmp_2_cfg_w (io_ptw_pmp_2_cfg_w),
    .io_pmp_2_cfg_r (io_ptw_pmp_2_cfg_r),
    .io_pmp_2_addr  (io_ptw_pmp_2_addr),
    .io_pmp_2_mask  (io_ptw_pmp_2_mask),
    .io_pmp_3_cfg_l (io_ptw_pmp_3_cfg_l),
    .io_pmp_3_cfg_a (io_ptw_pmp_3_cfg_a),
    .io_pmp_3_cfg_x (io_ptw_pmp_3_cfg_x),
    .io_pmp_3_cfg_w (io_ptw_pmp_3_cfg_w),
    .io_pmp_3_cfg_r (io_ptw_pmp_3_cfg_r),
    .io_pmp_3_addr  (io_ptw_pmp_3_addr),
    .io_pmp_3_mask  (io_ptw_pmp_3_mask),
    .io_pmp_4_cfg_l (io_ptw_pmp_4_cfg_l),
    .io_pmp_4_cfg_a (io_ptw_pmp_4_cfg_a),
    .io_pmp_4_cfg_x (io_ptw_pmp_4_cfg_x),
    .io_pmp_4_cfg_w (io_ptw_pmp_4_cfg_w),
    .io_pmp_4_cfg_r (io_ptw_pmp_4_cfg_r),
    .io_pmp_4_addr  (io_ptw_pmp_4_addr),
    .io_pmp_4_mask  (io_ptw_pmp_4_mask),
    .io_pmp_5_cfg_l (io_ptw_pmp_5_cfg_l),
    .io_pmp_5_cfg_a (io_ptw_pmp_5_cfg_a),
    .io_pmp_5_cfg_x (io_ptw_pmp_5_cfg_x),
    .io_pmp_5_cfg_w (io_ptw_pmp_5_cfg_w),
    .io_pmp_5_cfg_r (io_ptw_pmp_5_cfg_r),
    .io_pmp_5_addr  (io_ptw_pmp_5_addr),
    .io_pmp_5_mask  (io_ptw_pmp_5_mask),
    .io_pmp_6_cfg_l (io_ptw_pmp_6_cfg_l),
    .io_pmp_6_cfg_a (io_ptw_pmp_6_cfg_a),
    .io_pmp_6_cfg_x (io_ptw_pmp_6_cfg_x),
    .io_pmp_6_cfg_w (io_ptw_pmp_6_cfg_w),
    .io_pmp_6_cfg_r (io_ptw_pmp_6_cfg_r),
    .io_pmp_6_addr  (io_ptw_pmp_6_addr),
    .io_pmp_6_mask  (io_ptw_pmp_6_mask),
    .io_pmp_7_cfg_l (io_ptw_pmp_7_cfg_l),
    .io_pmp_7_cfg_a (io_ptw_pmp_7_cfg_a),
    .io_pmp_7_cfg_x (io_ptw_pmp_7_cfg_x),
    .io_pmp_7_cfg_w (io_ptw_pmp_7_cfg_w),
    .io_pmp_7_cfg_r (io_ptw_pmp_7_cfg_r),
    .io_pmp_7_addr  (io_ptw_pmp_7_addr),
    .io_pmp_7_mask  (io_ptw_pmp_7_mask),
    .io_addr        ({mpu_ppn[19:0], io_req_bits_vaddr[11:0]}),	// @[TLB.scala:399:20, :401:52, :404:15]
    .io_r           (_pmp_io_r),
    .io_w           (_pmp_io_w),
    .io_x           (_pmp_io_x)
  );
  OptimizationBarrier entries_barrier (	// @[package.scala:259:25]
    .io_x_ppn      (_entries_WIRE_1[40:21]),	// @[TLB.scala:159:77]
    .io_x_u        (_entries_WIRE_1[20]),	// @[TLB.scala:159:77]
    .io_x_ae_ptw   (_entries_WIRE_1[18]),	// @[TLB.scala:159:77]
    .io_x_ae_final (_entries_WIRE_1[17]),	// @[TLB.scala:159:77]
    .io_x_pf       (_entries_WIRE_1[16]),	// @[TLB.scala:159:77]
    .io_x_gf       (_entries_WIRE_1[15]),	// @[TLB.scala:159:77]
    .io_x_sw       (_entries_WIRE_1[14]),	// @[TLB.scala:159:77]
    .io_x_sx       (_entries_WIRE_1[13]),	// @[TLB.scala:159:77]
    .io_x_sr       (_entries_WIRE_1[12]),	// @[TLB.scala:159:77]
    .io_x_pw       (_entries_WIRE_1[8]),	// @[TLB.scala:159:77]
    .io_x_px       (_entries_WIRE_1[7]),	// @[TLB.scala:159:77]
    .io_x_pr       (_entries_WIRE_1[6]),	// @[TLB.scala:159:77]
    .io_x_ppp      (_entries_WIRE_1[5]),	// @[TLB.scala:159:77]
    .io_x_pal      (_entries_WIRE_1[4]),	// @[TLB.scala:159:77]
    .io_x_paa      (_entries_WIRE_1[3]),	// @[TLB.scala:159:77]
    .io_x_eff      (_entries_WIRE_1[2]),	// @[TLB.scala:159:77]
    .io_x_c        (_entries_WIRE_1[1]),	// @[TLB.scala:159:77]
    .io_y_ppn      (_entries_barrier_io_y_ppn),
    .io_y_u        (_entries_barrier_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_io_y_ae_final),
    .io_y_pf       (_entries_barrier_io_y_pf),
    .io_y_gf       (_entries_barrier_io_y_gf),
    .io_y_sw       (_entries_barrier_io_y_sw),
    .io_y_sx       (_entries_barrier_io_y_sx),
    .io_y_sr       (_entries_barrier_io_y_sr),
    .io_y_pw       (_entries_barrier_io_y_pw),
    .io_y_px       (_entries_barrier_io_y_px),
    .io_y_pr       (_entries_barrier_io_y_pr),
    .io_y_ppp      (_entries_barrier_io_y_ppp),
    .io_y_pal      (_entries_barrier_io_y_pal),
    .io_y_paa      (_entries_barrier_io_y_paa),
    .io_y_eff      (_entries_barrier_io_y_eff),
    .io_y_c        (_entries_barrier_io_y_c)
  );
  OptimizationBarrier entries_barrier_1 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_0_data_0[40:21]),	// @[TLB.scala:159:77, :328:30]
    .io_x_u        (superpage_entries_0_data_0[20]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_ptw   (superpage_entries_0_data_0[18]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_final (superpage_entries_0_data_0[17]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pf       (superpage_entries_0_data_0[16]),	// @[TLB.scala:159:77, :328:30]
    .io_x_gf       (superpage_entries_0_data_0[15]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sw       (superpage_entries_0_data_0[14]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sx       (superpage_entries_0_data_0[13]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sr       (superpage_entries_0_data_0[12]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pw       (superpage_entries_0_data_0[8]),	// @[TLB.scala:159:77, :328:30]
    .io_x_px       (superpage_entries_0_data_0[7]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pr       (superpage_entries_0_data_0[6]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ppp      (superpage_entries_0_data_0[5]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pal      (superpage_entries_0_data_0[4]),	// @[TLB.scala:159:77, :328:30]
    .io_x_paa      (superpage_entries_0_data_0[3]),	// @[TLB.scala:159:77, :328:30]
    .io_x_eff      (superpage_entries_0_data_0[2]),	// @[TLB.scala:159:77, :328:30]
    .io_x_c        (superpage_entries_0_data_0[1]),	// @[TLB.scala:159:77, :328:30]
    .io_y_ppn      (_entries_barrier_1_io_y_ppn),
    .io_y_u        (_entries_barrier_1_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_1_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_1_io_y_ae_final),
    .io_y_pf       (_entries_barrier_1_io_y_pf),
    .io_y_gf       (_entries_barrier_1_io_y_gf),
    .io_y_sw       (_entries_barrier_1_io_y_sw),
    .io_y_sx       (_entries_barrier_1_io_y_sx),
    .io_y_sr       (_entries_barrier_1_io_y_sr),
    .io_y_pw       (_entries_barrier_1_io_y_pw),
    .io_y_px       (_entries_barrier_1_io_y_px),
    .io_y_pr       (_entries_barrier_1_io_y_pr),
    .io_y_ppp      (_entries_barrier_1_io_y_ppp),
    .io_y_pal      (_entries_barrier_1_io_y_pal),
    .io_y_paa      (_entries_barrier_1_io_y_paa),
    .io_y_eff      (_entries_barrier_1_io_y_eff),
    .io_y_c        (_entries_barrier_1_io_y_c)
  );
  OptimizationBarrier entries_barrier_2 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_1_data_0[40:21]),	// @[TLB.scala:159:77, :328:30]
    .io_x_u        (superpage_entries_1_data_0[20]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_ptw   (superpage_entries_1_data_0[18]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_final (superpage_entries_1_data_0[17]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pf       (superpage_entries_1_data_0[16]),	// @[TLB.scala:159:77, :328:30]
    .io_x_gf       (superpage_entries_1_data_0[15]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sw       (superpage_entries_1_data_0[14]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sx       (superpage_entries_1_data_0[13]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sr       (superpage_entries_1_data_0[12]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pw       (superpage_entries_1_data_0[8]),	// @[TLB.scala:159:77, :328:30]
    .io_x_px       (superpage_entries_1_data_0[7]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pr       (superpage_entries_1_data_0[6]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ppp      (superpage_entries_1_data_0[5]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pal      (superpage_entries_1_data_0[4]),	// @[TLB.scala:159:77, :328:30]
    .io_x_paa      (superpage_entries_1_data_0[3]),	// @[TLB.scala:159:77, :328:30]
    .io_x_eff      (superpage_entries_1_data_0[2]),	// @[TLB.scala:159:77, :328:30]
    .io_x_c        (superpage_entries_1_data_0[1]),	// @[TLB.scala:159:77, :328:30]
    .io_y_ppn      (_entries_barrier_2_io_y_ppn),
    .io_y_u        (_entries_barrier_2_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_2_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_2_io_y_ae_final),
    .io_y_pf       (_entries_barrier_2_io_y_pf),
    .io_y_gf       (_entries_barrier_2_io_y_gf),
    .io_y_sw       (_entries_barrier_2_io_y_sw),
    .io_y_sx       (_entries_barrier_2_io_y_sx),
    .io_y_sr       (_entries_barrier_2_io_y_sr),
    .io_y_pw       (_entries_barrier_2_io_y_pw),
    .io_y_px       (_entries_barrier_2_io_y_px),
    .io_y_pr       (_entries_barrier_2_io_y_pr),
    .io_y_ppp      (_entries_barrier_2_io_y_ppp),
    .io_y_pal      (_entries_barrier_2_io_y_pal),
    .io_y_paa      (_entries_barrier_2_io_y_paa),
    .io_y_eff      (_entries_barrier_2_io_y_eff),
    .io_y_c        (_entries_barrier_2_io_y_c)
  );
  OptimizationBarrier entries_barrier_3 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_2_data_0[40:21]),	// @[TLB.scala:159:77, :328:30]
    .io_x_u        (superpage_entries_2_data_0[20]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_ptw   (superpage_entries_2_data_0[18]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_final (superpage_entries_2_data_0[17]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pf       (superpage_entries_2_data_0[16]),	// @[TLB.scala:159:77, :328:30]
    .io_x_gf       (superpage_entries_2_data_0[15]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sw       (superpage_entries_2_data_0[14]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sx       (superpage_entries_2_data_0[13]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sr       (superpage_entries_2_data_0[12]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pw       (superpage_entries_2_data_0[8]),	// @[TLB.scala:159:77, :328:30]
    .io_x_px       (superpage_entries_2_data_0[7]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pr       (superpage_entries_2_data_0[6]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ppp      (superpage_entries_2_data_0[5]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pal      (superpage_entries_2_data_0[4]),	// @[TLB.scala:159:77, :328:30]
    .io_x_paa      (superpage_entries_2_data_0[3]),	// @[TLB.scala:159:77, :328:30]
    .io_x_eff      (superpage_entries_2_data_0[2]),	// @[TLB.scala:159:77, :328:30]
    .io_x_c        (superpage_entries_2_data_0[1]),	// @[TLB.scala:159:77, :328:30]
    .io_y_ppn      (_entries_barrier_3_io_y_ppn),
    .io_y_u        (_entries_barrier_3_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_3_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_3_io_y_ae_final),
    .io_y_pf       (_entries_barrier_3_io_y_pf),
    .io_y_gf       (_entries_barrier_3_io_y_gf),
    .io_y_sw       (_entries_barrier_3_io_y_sw),
    .io_y_sx       (_entries_barrier_3_io_y_sx),
    .io_y_sr       (_entries_barrier_3_io_y_sr),
    .io_y_pw       (_entries_barrier_3_io_y_pw),
    .io_y_px       (_entries_barrier_3_io_y_px),
    .io_y_pr       (_entries_barrier_3_io_y_pr),
    .io_y_ppp      (_entries_barrier_3_io_y_ppp),
    .io_y_pal      (_entries_barrier_3_io_y_pal),
    .io_y_paa      (_entries_barrier_3_io_y_paa),
    .io_y_eff      (_entries_barrier_3_io_y_eff),
    .io_y_c        (_entries_barrier_3_io_y_c)
  );
  OptimizationBarrier entries_barrier_4 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_3_data_0[40:21]),	// @[TLB.scala:159:77, :328:30]
    .io_x_u        (superpage_entries_3_data_0[20]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_ptw   (superpage_entries_3_data_0[18]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ae_final (superpage_entries_3_data_0[17]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pf       (superpage_entries_3_data_0[16]),	// @[TLB.scala:159:77, :328:30]
    .io_x_gf       (superpage_entries_3_data_0[15]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sw       (superpage_entries_3_data_0[14]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sx       (superpage_entries_3_data_0[13]),	// @[TLB.scala:159:77, :328:30]
    .io_x_sr       (superpage_entries_3_data_0[12]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pw       (superpage_entries_3_data_0[8]),	// @[TLB.scala:159:77, :328:30]
    .io_x_px       (superpage_entries_3_data_0[7]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pr       (superpage_entries_3_data_0[6]),	// @[TLB.scala:159:77, :328:30]
    .io_x_ppp      (superpage_entries_3_data_0[5]),	// @[TLB.scala:159:77, :328:30]
    .io_x_pal      (superpage_entries_3_data_0[4]),	// @[TLB.scala:159:77, :328:30]
    .io_x_paa      (superpage_entries_3_data_0[3]),	// @[TLB.scala:159:77, :328:30]
    .io_x_eff      (superpage_entries_3_data_0[2]),	// @[TLB.scala:159:77, :328:30]
    .io_x_c        (superpage_entries_3_data_0[1]),	// @[TLB.scala:159:77, :328:30]
    .io_y_ppn      (_entries_barrier_4_io_y_ppn),
    .io_y_u        (_entries_barrier_4_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_4_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_4_io_y_ae_final),
    .io_y_pf       (_entries_barrier_4_io_y_pf),
    .io_y_gf       (_entries_barrier_4_io_y_gf),
    .io_y_sw       (_entries_barrier_4_io_y_sw),
    .io_y_sx       (_entries_barrier_4_io_y_sx),
    .io_y_sr       (_entries_barrier_4_io_y_sr),
    .io_y_pw       (_entries_barrier_4_io_y_pw),
    .io_y_px       (_entries_barrier_4_io_y_px),
    .io_y_pr       (_entries_barrier_4_io_y_pr),
    .io_y_ppp      (_entries_barrier_4_io_y_ppp),
    .io_y_pal      (_entries_barrier_4_io_y_pal),
    .io_y_paa      (_entries_barrier_4_io_y_paa),
    .io_y_eff      (_entries_barrier_4_io_y_eff),
    .io_y_c        (_entries_barrier_4_io_y_c)
  );
  OptimizationBarrier entries_barrier_5 (	// @[package.scala:259:25]
    .io_x_ppn      (special_entry_data_0[40:21]),	// @[TLB.scala:159:77, :333:56]
    .io_x_u        (special_entry_data_0[20]),	// @[TLB.scala:159:77, :333:56]
    .io_x_ae_ptw   (special_entry_data_0[18]),	// @[TLB.scala:159:77, :333:56]
    .io_x_ae_final (special_entry_data_0[17]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pf       (special_entry_data_0[16]),	// @[TLB.scala:159:77, :333:56]
    .io_x_gf       (special_entry_data_0[15]),	// @[TLB.scala:159:77, :333:56]
    .io_x_sw       (special_entry_data_0[14]),	// @[TLB.scala:159:77, :333:56]
    .io_x_sx       (special_entry_data_0[13]),	// @[TLB.scala:159:77, :333:56]
    .io_x_sr       (special_entry_data_0[12]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pw       (special_entry_data_0[8]),	// @[TLB.scala:159:77, :333:56]
    .io_x_px       (special_entry_data_0[7]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pr       (special_entry_data_0[6]),	// @[TLB.scala:159:77, :333:56]
    .io_x_ppp      (special_entry_data_0[5]),	// @[TLB.scala:159:77, :333:56]
    .io_x_pal      (special_entry_data_0[4]),	// @[TLB.scala:159:77, :333:56]
    .io_x_paa      (special_entry_data_0[3]),	// @[TLB.scala:159:77, :333:56]
    .io_x_eff      (special_entry_data_0[2]),	// @[TLB.scala:159:77, :333:56]
    .io_x_c        (special_entry_data_0[1]),	// @[TLB.scala:159:77, :333:56]
    .io_y_ppn      (_entries_barrier_5_io_y_ppn),
    .io_y_u        (_entries_barrier_5_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_5_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_5_io_y_ae_final),
    .io_y_pf       (_entries_barrier_5_io_y_pf),
    .io_y_gf       (_entries_barrier_5_io_y_gf),
    .io_y_sw       (_entries_barrier_5_io_y_sw),
    .io_y_sx       (_entries_barrier_5_io_y_sx),
    .io_y_sr       (_entries_barrier_5_io_y_sr),
    .io_y_pw       (_entries_barrier_5_io_y_pw),
    .io_y_px       (_entries_barrier_5_io_y_px),
    .io_y_pr       (_entries_barrier_5_io_y_pr),
    .io_y_ppp      (_entries_barrier_5_io_y_ppp),
    .io_y_pal      (_entries_barrier_5_io_y_pal),
    .io_y_paa      (_entries_barrier_5_io_y_paa),
    .io_y_eff      (_entries_barrier_5_io_y_eff),
    .io_y_c        (_entries_barrier_5_io_y_c)
  );
  assign io_resp_miss = io_ptw_resp_valid | tlb_miss | multipleHits;	// @[Misc.scala:182:49, TLB.scala:602:64, :640:64]
  assign io_resp_paddr = {(hitsVec_0 ? _entries_barrier_io_y_ppn : 20'h0) | (hitsVec_1 ? {_entries_barrier_1_io_y_ppn[19:18], (superpage_hits_ignore_1 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_1_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_1_io_y_ppn[8:0]} : 20'h0) | (hitsVec_2 ? {_entries_barrier_2_io_y_ppn[19:18], (superpage_hits_ignore_4 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_2_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_2_io_y_ppn[8:0]} : 20'h0) | (hitsVec_3 ? {_entries_barrier_3_io_y_ppn[19:18], (superpage_hits_ignore_7 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_3_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_3_io_y_ppn[8:0]} : 20'h0) | (hitsVec_4 ? {_entries_barrier_4_io_y_ppn[19:18], (superpage_hits_ignore_10 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_4_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_4_io_y_ppn[8:0]} : 20'h0) | (hitsVec_5 ? {_entries_barrier_5_io_y_ppn[19:18], _GEN | _entries_barrier_5_io_y_ppn[17:9], _GEN_0 | _entries_barrier_5_io_y_ppn[8:0]} : 20'h0) | (_vm_enabled_T_1 ? 20'h0 : io_req_bits_vaddr[31:12]), io_req_bits_vaddr[11:0]};	// @[Cat.scala:33:92, Mux.scala:27:73, TLB.scala:171:28, :172:79, :184:26, :187:{28,47}, :322:30, :386:45, :401:52, :430:44, :491:125, package.scala:259:25]
  assign io_resp_pf_inst = bad_va | (|((~((io_req_bits_prv[0] ? ~{_entries_barrier_5_io_y_u, _entries_barrier_4_io_y_u, _entries_barrier_3_io_y_u, _entries_barrier_2_io_y_u, _entries_barrier_1_io_y_u, _entries_barrier_io_y_u} : {_entries_barrier_5_io_y_u, _entries_barrier_4_io_y_u, _entries_barrier_3_io_y_u, _entries_barrier_2_io_y_u, _entries_barrier_1_io_y_u, _entries_barrier_io_y_u}) & {_entries_barrier_5_io_y_sx, _entries_barrier_4_io_y_sx, _entries_barrier_3_io_y_sx, _entries_barrier_2_io_y_sx, _entries_barrier_1_io_y_sx, _entries_barrier_io_y_sx}) & {~_entries_barrier_5_io_y_ae_ptw, ~_entries_barrier_4_io_y_ae_ptw, ~_entries_barrier_3_io_y_ae_ptw, ~_entries_barrier_2_io_y_ae_ptw, ~_entries_barrier_1_io_y_ae_ptw, ~_entries_barrier_io_y_ae_ptw} | {_entries_barrier_5_io_y_pf, _entries_barrier_4_io_y_pf, _entries_barrier_3_io_y_pf, _entries_barrier_2_io_y_pf, _entries_barrier_1_io_y_pf, _entries_barrier_io_y_pf}) & {~_entries_barrier_5_io_y_gf, ~_entries_barrier_4_io_y_gf, ~_entries_barrier_3_io_y_gf, ~_entries_barrier_2_io_y_gf, ~_entries_barrier_1_io_y_gf, ~_entries_barrier_io_y_gf} & {hitsVec_5, hitsVec_4, hitsVec_3, hitsVec_2, hitsVec_1, hitsVec_0}));	// @[Cat.scala:33:92, TLB.scala:357:20, :430:44, :505:{22,31}, :511:40, :557:34, :586:{73,106}, :588:{25,34,51}, :624:{29,47,55}, package.scala:259:25]
  assign io_resp_ae_inst = |(~({{2{newEntry_px}}, _entries_barrier_4_io_y_px, _entries_barrier_3_io_y_px, _entries_barrier_2_io_y_px, _entries_barrier_1_io_y_px, _entries_barrier_io_y_px} & {1'h1, ~(_entries_barrier_5_io_y_ae_ptw | _entries_barrier_5_io_y_ae_final), ~(_entries_barrier_4_io_y_ae_ptw | _entries_barrier_4_io_y_ae_final), ~(_entries_barrier_3_io_y_ae_ptw | _entries_barrier_3_io_y_ae_final), ~(_entries_barrier_2_io_y_ae_ptw | _entries_barrier_2_io_y_ae_final), ~(_entries_barrier_1_io_y_ae_ptw | _entries_barrier_1_io_y_ae_final), ~(_entries_barrier_io_y_ae_ptw | _entries_barrier_io_y_ae_final)}) & hits);	// @[Bitwise.scala:77:12, Cat.scala:33:92, TLB.scala:424:65, :518:104, :522:{87,89}, :632:{23,33,41}, package.scala:259:25]
  assign io_resp_cacheable = |({{2{newEntry_c}}, _entries_barrier_4_io_y_c, _entries_barrier_3_io_y_c, _entries_barrier_2_io_y_c, _entries_barrier_1_io_y_c, _entries_barrier_io_y_c} & hits);	// @[Bitwise.scala:77:12, Cat.scala:33:92, TLB.scala:413:19, :637:{33,41}, package.scala:259:25]
  assign io_ptw_req_valid = _T_22;	// @[package.scala:16:47]
  assign io_ptw_req_bits_valid = ~io_kill;	// @[TLB.scala:650:28]
  assign io_ptw_req_bits_bits_addr = r_refill_tag;	// @[TLB.scala:341:25]
  assign io_ptw_req_bits_bits_need_gpa = r_need_gpa;	// @[TLB.scala:348:23]
  assign io_ptw_req_bits_bits_vstage1 = r_vstage1_en;	// @[TLB.scala:346:25]
  assign io_ptw_req_bits_bits_stage2 = r_stage2_en;	// @[TLB.scala:347:24]
endmodule

