// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLBroadcast(
  input         clock,
                reset,
                auto_in_a_valid,
  input  [2:0]  auto_in_a_bits_opcode,
                auto_in_a_bits_param,
                auto_in_a_bits_size,
  input  [4:0]  auto_in_a_bits_source,
  input  [30:0] auto_in_a_bits_address,
  input  [7:0]  auto_in_a_bits_mask,
  input  [63:0] auto_in_a_bits_data,
  input         auto_in_d_ready,
                auto_out_a_ready,
                auto_out_d_valid,
  input  [2:0]  auto_out_d_bits_opcode,
  input  [1:0]  auto_out_d_bits_param,
  input  [2:0]  auto_out_d_bits_size,
  input  [6:0]  auto_out_d_bits_source,
  input         auto_out_d_bits_denied,
  input  [63:0] auto_out_d_bits_data,
  input         auto_out_d_bits_corrupt,
  output        auto_in_a_ready,
                auto_in_d_valid,
  output [2:0]  auto_in_d_bits_opcode,
  output [1:0]  auto_in_d_bits_param,
  output [2:0]  auto_in_d_bits_size,
  output [4:0]  auto_in_d_bits_source,
  output [1:0]  auto_in_d_bits_sink,
  output        auto_in_d_bits_denied,
  output [63:0] auto_in_d_bits_data,
  output        auto_in_d_bits_corrupt,
                auto_out_a_valid,
  output [2:0]  auto_out_a_bits_opcode,
                auto_out_a_bits_param,
                auto_out_a_bits_size,
  output [6:0]  auto_out_a_bits_source,
  output [30:0] auto_out_a_bits_address,
  output [7:0]  auto_out_a_bits_mask,
  output [63:0] auto_out_a_bits_data,
  output        auto_out_d_ready
);

  wire        out_1_ready;	// @[Arbiter.scala:124:31]
  wire [2:0]  out_1_bits_opcode;	// @[Broadcast.scala:131:21, :132:24, :133:30]
  wire [4:0]  out_1_bits_source;	// @[Broadcast.scala:131:21]
  wire        winnerQual_1;	// @[Broadcast.scala:130:48]
  wire        _TLBroadcastTracker_3_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_3_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_3_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_3_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_3_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [6:0]  _TLBroadcastTracker_3_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [30:0] _TLBroadcastTracker_3_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_3_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_3_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [4:0]  _TLBroadcastTracker_3_io_source;	// @[Broadcast.scala:108:15]
  wire [24:0] _TLBroadcastTracker_3_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_3_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_3_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_2_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_2_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_2_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [6:0]  _TLBroadcastTracker_2_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [30:0] _TLBroadcastTracker_2_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_2_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_2_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [4:0]  _TLBroadcastTracker_2_io_source;	// @[Broadcast.scala:108:15]
  wire [24:0] _TLBroadcastTracker_2_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_1_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_1_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_1_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [6:0]  _TLBroadcastTracker_1_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [30:0] _TLBroadcastTracker_1_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_1_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_1_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [4:0]  _TLBroadcastTracker_1_io_source;	// @[Broadcast.scala:108:15]
  wire [24:0] _TLBroadcastTracker_1_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [6:0]  _TLBroadcastTracker_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [30:0] _TLBroadcastTracker_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [4:0]  _TLBroadcastTracker_io_source;	// @[Broadcast.scala:108:15]
  wire [24:0] _TLBroadcastTracker_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _T_14 = auto_out_d_bits_source[6:5] == 2'h1;	// @[Broadcast.scala:119:37, :120:27, :134:51]
  wire        _T_82 = out_1_ready & winnerQual_1;	// @[Arbiter.scala:124:31, Broadcast.scala:130:48, Decoupled.scala:51:35]
  wire [12:0] _GEN = {10'h0, auto_out_d_bits_size};	// @[package.scala:235:71]
  wire [12:0] _beats1_decode_T_1 = 13'h3F << _GEN;	// @[package.scala:235:71]
  reg  [2:0]  counter;	// @[Edges.scala:229:27]
  wire        first = counter == 3'h0;	// @[Edges.scala:229:27, :231:25]
  wire        last = counter == 3'h1 | (out_1_bits_opcode[0] ? ~(_beats1_decode_T_1[5:3]) : 3'h0) == 3'h0;	// @[Broadcast.scala:131:21, :132:24, :133:30, Edges.scala:106:36, :221:14, :229:27, :232:{25,33,43}, package.scala:235:{46,71,76}]
  wire [3:0]  _T_24 = {_TLBroadcastTracker_3_io_need_d & _TLBroadcastTracker_3_io_source == out_1_bits_source, _TLBroadcastTracker_2_io_need_d & _TLBroadcastTracker_2_io_source == out_1_bits_source, _TLBroadcastTracker_1_io_need_d & _TLBroadcastTracker_1_io_source == out_1_bits_source, _TLBroadcastTracker_io_need_d & _TLBroadcastTracker_io_source == out_1_bits_source};	// @[Broadcast.scala:108:15, :124:{62,74,102}, :131:21]
  reg  [3:0]  r;	// @[Reg.scala:19:16]
  wire [3:0]  _T_25 = first ? _T_24 : r;	// @[Broadcast.scala:124:102, Edges.scala:231:25, Reg.scala:19:16, package.scala:80:42]
  wire        x1_d_ready = out_1_ready | _T_14;	// @[Arbiter.scala:124:31, Broadcast.scala:120:27, :129:50]
  assign winnerQual_1 = auto_out_d_valid & ~_T_14;	// @[Broadcast.scala:120:27, :126:31, :130:48]
  assign out_1_bits_source = auto_out_d_bits_source[4:0];	// @[Broadcast.scala:131:21]
  assign out_1_bits_opcode = auto_out_d_bits_source[6] ? (auto_out_d_bits_opcode[0] ? 3'h5 : 3'h6) : auto_out_d_bits_opcode;	// @[Broadcast.scala:119:37, :131:21, :132:{19,24}, :133:{30,36}, Edges.scala:106:36]
  wire        _T_56 = auto_out_d_bits_opcode[0] | ~(auto_out_d_bits_source[6]);	// @[Broadcast.scala:119:37, :132:19, :141:{34,37}, Edges.scala:106:36]
  wire        _T_86 = x1_d_ready & auto_out_d_valid;	// @[Broadcast.scala:129:50, Decoupled.scala:51:35]
  reg  [2:0]  beatsLeft;	// @[Arbiter.scala:88:30]
  wire        idle = beatsLeft == 3'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:229:27]
  reg         state_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_1 = idle ? winnerQual_1 : state_1;	// @[Arbiter.scala:89:28, :117:26, :118:30, Broadcast.scala:130:48]
  assign out_1_ready = auto_in_d_ready & (idle | state_1);	// @[Arbiter.scala:89:28, :117:26, :122:24, :124:31]
  wire        out_2_valid = (idle | state_1) & winnerQual_1;	// @[Arbiter.scala:89:28, :117:26, :126:29, Broadcast.scala:130:48]
  reg  [2:0]  beatsLeft_1;	// @[Arbiter.scala:88:30]
  wire        idle_1 = beatsLeft_1 == 3'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:229:27]
  wire        _GEN_0 = _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_io_out_a_valid;	// @[Broadcast.scala:108:15, package.scala:245:43]
  wire        _GEN_1 = _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_io_out_a_valid;	// @[Broadcast.scala:108:15, package.scala:245:43]
  wire        earlyWinner_1_2 = ~_TLBroadcastTracker_io_out_a_valid & _TLBroadcastTracker_1_io_out_a_valid;	// @[Arbiter.scala:17:61, :98:79, Broadcast.scala:108:15]
  wire        earlyWinner_1_3 = ~_GEN_0 & _TLBroadcastTracker_2_io_out_a_valid;	// @[Arbiter.scala:17:61, :98:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        earlyWinner_1_4 = ~_GEN_1 & _TLBroadcastTracker_3_io_out_a_valid;	// @[Arbiter.scala:17:61, :98:79, Broadcast.scala:108:15, package.scala:245:43]
  reg         state_1_1;	// @[Arbiter.scala:117:26]
  reg         state_1_2;	// @[Arbiter.scala:117:26]
  reg         state_1_3;	// @[Arbiter.scala:117:26]
  reg         state_1_4;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_1_1 = idle_1 ? _TLBroadcastTracker_io_out_a_valid : state_1_1;	// @[Arbiter.scala:89:28, :117:26, :118:30, Broadcast.scala:108:15]
  wire        muxStateEarly_1_2 = idle_1 ? earlyWinner_1_2 : state_1_2;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1_3 = idle_1 ? earlyWinner_1_3 : state_1_3;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1_4 = idle_1 ? earlyWinner_1_4 : state_1_4;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        out_8_valid = idle_1 ? _TLBroadcastTracker_io_out_a_valid | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid : state_1_1 & _TLBroadcastTracker_io_out_a_valid | state_1_2 & _TLBroadcastTracker_1_io_out_a_valid | state_1_3 & _TLBroadcastTracker_2_io_out_a_valid | state_1_4 & _TLBroadcastTracker_3_io_out_a_valid;	// @[Arbiter.scala:89:28, :117:26, :126:{29,56}, Broadcast.scala:108:15, Mux.scala:27:73]
  reg  [2:0]  counter_2;	// @[Edges.scala:229:27]
  wire        first_2 = counter_2 == 3'h0;	// @[Edges.scala:229:27, :231:25]
  wire        _WIRE_126_0 = _TLBroadcastTracker_io_line == auto_in_a_bits_address[30:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire        _WIRE_126_1 = _TLBroadcastTracker_1_io_line == auto_in_a_bits_address[30:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire        _WIRE_126_2 = _TLBroadcastTracker_2_io_line == auto_in_a_bits_address[30:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire        _WIRE_126_3 = _TLBroadcastTracker_3_io_line == auto_in_a_bits_address[30:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire [3:0]  _GEN_2 = (|{_WIRE_126_3, _WIRE_126_2, _WIRE_126_1, _WIRE_126_0}) ? {_WIRE_126_3, _WIRE_126_2, _WIRE_126_1, _WIRE_126_0} : {_TLBroadcastTracker_3_io_idle, _TLBroadcastTracker_2_io_idle, _TLBroadcastTracker_1_io_idle, _TLBroadcastTracker_io_idle} & {~(_TLBroadcastTracker_2_io_idle | _TLBroadcastTracker_1_io_idle | _TLBroadcastTracker_io_idle), ~(_TLBroadcastTracker_1_io_idle | _TLBroadcastTracker_io_idle), ~_TLBroadcastTracker_io_idle, 1'h1};	// @[Broadcast.scala:108:15, :237:{62,100}, :238:40, :239:{39,41,64}, :240:30, :246:59, package.scala:245:43]
  wire [3:0]  _GEN_3 = _GEN_2 & {_TLBroadcastTracker_3_io_in_a_ready, _TLBroadcastTracker_2_io_in_a_ready, _TLBroadcastTracker_1_io_in_a_ready, _TLBroadcastTracker_io_in_a_ready};	// @[Broadcast.scala:108:15, :240:30, :242:41]
  wire [12:0] _decode_T_5 = 13'h3F << _GEN;	// @[package.scala:235:71]
  wire [12:0] _decode_T_25 = 13'h3F << _TLBroadcastTracker_3_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_21 = 13'h3F << _TLBroadcastTracker_2_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_17 = 13'h3F << _TLBroadcastTracker_1_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_13 = 13'h3F << _TLBroadcastTracker_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _beats1_decode_T_9 = 13'h3F << auto_in_a_bits_size;	// @[package.scala:235:71]
  wire        winnerQual_1_2 = ~_TLBroadcastTracker_io_out_a_valid & _TLBroadcastTracker_1_io_out_a_valid;	// @[Arbiter.scala:17:61, :99:79, Broadcast.scala:108:15]
  wire        winnerQual_1_3 = ~_GEN_0 & _TLBroadcastTracker_2_io_out_a_valid;	// @[Arbiter.scala:17:61, :99:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        winnerQual_1_4 = ~_GEN_1 & _TLBroadcastTracker_3_io_out_a_valid;	// @[Arbiter.scala:17:61, :99:79, Broadcast.scala:108:15, package.scala:245:43]
  always @(posedge clock) begin
    if (reset) begin
      counter <= 3'h0;	// @[Edges.scala:229:27]
      beatsLeft <= 3'h0;	// @[Arbiter.scala:88:30, Edges.scala:229:27]
      state_1 <= 1'h0;	// @[Arbiter.scala:117:26, ReadyValidCancel.scala:68:19]
      beatsLeft_1 <= 3'h0;	// @[Arbiter.scala:88:30, Edges.scala:229:27]
      state_1_1 <= 1'h0;	// @[Arbiter.scala:117:26, ReadyValidCancel.scala:68:19]
      state_1_2 <= 1'h0;	// @[Arbiter.scala:117:26, ReadyValidCancel.scala:68:19]
      state_1_3 <= 1'h0;	// @[Arbiter.scala:117:26, ReadyValidCancel.scala:68:19]
      state_1_4 <= 1'h0;	// @[Arbiter.scala:117:26, ReadyValidCancel.scala:68:19]
      counter_2 <= 3'h0;	// @[Edges.scala:229:27]
    end
    else begin
      if (_T_82) begin	// @[Decoupled.scala:51:35]
        if (first) begin	// @[Edges.scala:231:25]
          if (out_1_bits_opcode[0])	// @[Broadcast.scala:131:21, :132:24, :133:30, Edges.scala:106:36]
            counter <= ~(_beats1_decode_T_1[5:3]);	// @[Edges.scala:229:27, package.scala:235:{46,71,76}]
          else	// @[Edges.scala:106:36]
            counter <= 3'h0;	// @[Edges.scala:229:27]
        end
        else	// @[Edges.scala:231:25]
          counter <= counter - 3'h1;	// @[Edges.scala:229:27, :230:28]
      end
      if (idle & auto_in_d_ready) begin	// @[Arbiter.scala:89:28, :90:24]
        if (winnerQual_1 & out_1_bits_opcode[0])	// @[Arbiter.scala:112:73, Broadcast.scala:130:48, :131:21, :132:24, :133:30, Edges.scala:106:36, :221:14]
          beatsLeft <= ~(_decode_T_5[5:3]);	// @[Arbiter.scala:88:30, package.scala:235:{46,71,76}]
        else	// @[Arbiter.scala:112:73, Edges.scala:221:14]
          beatsLeft <= 3'h0;	// @[Arbiter.scala:88:30, Edges.scala:229:27]
      end
      else	// @[Arbiter.scala:90:24]
        beatsLeft <= beatsLeft - {2'h0, auto_in_d_ready & out_2_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, Bundles.scala:262:74, ReadyValidCancel.scala:49:33]
      if (idle)	// @[Arbiter.scala:89:28]
        state_1 <= winnerQual_1;	// @[Arbiter.scala:117:26, Broadcast.scala:130:48]
      if (idle_1 & auto_out_a_ready)	// @[Arbiter.scala:89:28, :90:24]
        beatsLeft_1 <= (_TLBroadcastTracker_io_out_a_valid & ~(_TLBroadcastTracker_io_out_a_bits_opcode[2]) ? ~(_decode_T_13[5:3]) : 3'h0) | (winnerQual_1_2 & ~(_TLBroadcastTracker_1_io_out_a_bits_opcode[2]) ? ~(_decode_T_17[5:3]) : 3'h0) | (winnerQual_1_3 & ~(_TLBroadcastTracker_2_io_out_a_bits_opcode[2]) ? ~(_decode_T_21[5:3]) : 3'h0) | (winnerQual_1_4 & ~(_TLBroadcastTracker_3_io_out_a_bits_opcode[2]) ? ~(_decode_T_25[5:3]) : 3'h0);	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Broadcast.scala:108:15, Edges.scala:92:{28,37}, :221:14, :229:27, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_1 <= beatsLeft_1 - {2'h0, auto_out_a_ready & out_8_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, Bundles.scala:262:74, ReadyValidCancel.scala:49:33]
      if (idle_1) begin	// @[Arbiter.scala:89:28]
        state_1_1 <= _TLBroadcastTracker_io_out_a_valid;	// @[Arbiter.scala:117:26, Broadcast.scala:108:15]
        state_1_2 <= winnerQual_1_2;	// @[Arbiter.scala:99:79, :117:26]
        state_1_3 <= winnerQual_1_3;	// @[Arbiter.scala:99:79, :117:26]
        state_1_4 <= winnerQual_1_4;	// @[Arbiter.scala:99:79, :117:26]
      end
      if ((|_GEN_3) & auto_in_a_valid) begin	// @[Broadcast.scala:242:{41,58}, Decoupled.scala:51:35]
        if (first_2) begin	// @[Edges.scala:231:25]
          if (auto_in_a_bits_opcode[2])	// @[Edges.scala:92:37]
            counter_2 <= 3'h0;	// @[Edges.scala:229:27]
          else	// @[Edges.scala:92:37]
            counter_2 <= ~(_beats1_decode_T_9[5:3]);	// @[Edges.scala:229:27, package.scala:235:{46,71,76}]
        end
        else	// @[Edges.scala:231:25]
          counter_2 <= counter_2 - 3'h1;	// @[Edges.scala:229:27, :230:28]
      end
    end
    if (first)	// @[Edges.scala:231:25]
      r <= _T_24;	// @[Broadcast.scala:124:102, Reg.scala:19:16]
  end // always @(posedge)
  `ifndef SYNTHESIS
    wire         prefixOR_3 = _TLBroadcastTracker_io_out_a_valid | earlyWinner_1_2;	// @[Arbiter.scala:98:79, :105:53, Broadcast.scala:108:15]
    always @(posedge clock) begin	// @[Broadcast.scala:126:14]
      if (~reset & ~(~auto_out_d_valid | ~_T_14 | auto_out_d_bits_opcode == 3'h0)) begin	// @[Broadcast.scala:120:27, :126:{14,15,31,39,60}, Edges.scala:229:27]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:126:14]
          $error("Assertion failed\n    at Broadcast.scala:126 assert (!out.d.valid || !d_drop || out.d.bits.opcode === TLMessages.AccessAck)\n");	// @[Broadcast.scala:126:14]
        if (`STOP_COND_)	// @[Broadcast.scala:126:14]
          $fatal;	// @[Broadcast.scala:126:14]
      end
      if (~reset & ~(~winnerQual_1 | (|_T_25) | out_1_bits_opcode == 3'h6)) begin	// @[Broadcast.scala:130:48, :131:21, :132:24, :133:{30,36}, :138:{14,15,31,47,75}, package.scala:80:42]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:138:14]
          $error("Assertion failed\n    at Broadcast.scala:138 assert (!d_normal.valid || (d_trackerOH.orR || d_normal.bits.opcode === TLMessages.ReleaseAck))\n");	// @[Broadcast.scala:138:14]
        if (`STOP_COND_)	// @[Broadcast.scala:138:14]
          $fatal;	// @[Broadcast.scala:138:14]
      end
      if (~reset & ~((~_TLBroadcastTracker_io_out_a_valid | ~earlyWinner_1_2) & (~prefixOR_3 | ~earlyWinner_1_3) & (~(prefixOR_3 | earlyWinner_1_3) | ~earlyWinner_1_4))) begin	// @[Arbiter.scala:98:79, :105:53, :106:{13,61,64,67,82}, Broadcast.scala:108:15]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~(_TLBroadcastTracker_io_out_a_valid | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid) | _TLBroadcastTracker_io_out_a_valid | earlyWinner_1_2 | earlyWinner_1_3 | earlyWinner_1_4)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}, Broadcast.scala:108:15]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~(_TLBroadcastTracker_io_out_a_valid | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid) | _TLBroadcastTracker_io_out_a_valid | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid)) begin	// @[Arbiter.scala:109:{14,15,36,41}, Broadcast.scala:108:15]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:109:14]
          $error("Assertion failed\n    at Arbiter.scala:109 assert (!validQuals .reduce(_||_) || validQuals .reduce(_||_))\n");	// @[Arbiter.scala:109:14]
        if (`STOP_COND_)	// @[Arbiter.scala:109:14]
          $fatal;	// @[Arbiter.scala:109:14]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        counter = _RANDOM_0[2:0];	// @[Edges.scala:229:27]
        r = _RANDOM_0[6:3];	// @[Edges.scala:229:27, Reg.scala:19:16]
        beatsLeft = _RANDOM_0[12:10];	// @[Arbiter.scala:88:30, Edges.scala:229:27]
        state_1 = _RANDOM_0[14];	// @[Arbiter.scala:117:26, Edges.scala:229:27]
        beatsLeft_1 = _RANDOM_0[17:15];	// @[Arbiter.scala:88:30, Edges.scala:229:27]
        state_1_1 = _RANDOM_0[19];	// @[Arbiter.scala:117:26, Edges.scala:229:27]
        state_1_2 = _RANDOM_0[20];	// @[Arbiter.scala:117:26, Edges.scala:229:27]
        state_1_3 = _RANDOM_0[21];	// @[Arbiter.scala:117:26, Edges.scala:229:27]
        state_1_4 = _RANDOM_0[22];	// @[Arbiter.scala:117:26, Edges.scala:229:27]
        counter_2 = _RANDOM_1[21:19];	// @[Edges.scala:229:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  TLBroadcastTracker TLBroadcastTracker (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (first_2),	// @[Edges.scala:231:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_2[0]),	// @[Broadcast.scala:240:30, :245:35, :246:36]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 | state_1_1)),	// @[Arbiter.scala:89:28, :117:26, :122:24, :124:31]
    .io_probedack          (_T_25[0] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_d_last             (_T_25[0] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:232:33, package.scala:80:42]
    .io_in_a_ready         (_TLBroadcastTracker_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_io_source),
    .io_line               (_TLBroadcastTracker_io_line),
    .io_idle               (_TLBroadcastTracker_io_idle),
    .io_need_d             (_TLBroadcastTracker_io_need_d)
  );
  TLBroadcastTracker_1 TLBroadcastTracker_1 (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (first_2),	// @[Edges.scala:231:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_2[1]),	// @[Broadcast.scala:240:30, :245:35, :246:36]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~_TLBroadcastTracker_io_out_a_valid : state_1_2)),	// @[Arbiter.scala:17:61, :89:28, :117:26, :122:24, :124:31, Broadcast.scala:108:15]
    .io_probedack          (_T_25[1] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_d_last             (_T_25[1] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:232:33, package.scala:80:42]
    .io_in_a_ready         (_TLBroadcastTracker_1_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_1_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_1_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_1_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_1_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_1_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_1_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_1_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_1_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_1_io_source),
    .io_line               (_TLBroadcastTracker_1_io_line),
    .io_idle               (_TLBroadcastTracker_1_io_idle),
    .io_need_d             (_TLBroadcastTracker_1_io_need_d)
  );
  TLBroadcastTracker_2 TLBroadcastTracker_2 (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (first_2),	// @[Edges.scala:231:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_2[2]),	// @[Broadcast.scala:240:30, :245:35, :246:36]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~_GEN_0 : state_1_3)),	// @[Arbiter.scala:17:61, :89:28, :117:26, :122:24, :124:31, package.scala:245:43]
    .io_probedack          (_T_25[2] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_d_last             (_T_25[2] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:232:33, package.scala:80:42]
    .io_in_a_ready         (_TLBroadcastTracker_2_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_2_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_2_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_2_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_2_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_2_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_2_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_2_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_2_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_2_io_source),
    .io_line               (_TLBroadcastTracker_2_io_line),
    .io_idle               (_TLBroadcastTracker_2_io_idle),
    .io_need_d             (_TLBroadcastTracker_2_io_need_d)
  );
  TLBroadcastTracker_3 TLBroadcastTracker_3 (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (first_2),	// @[Edges.scala:231:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_2[3]),	// @[Broadcast.scala:240:30, :245:35, :246:36]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~_GEN_1 : state_1_4)),	// @[Arbiter.scala:17:61, :89:28, :117:26, :122:24, :124:31, package.scala:245:43]
    .io_probedack          (_T_25[3] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_d_last             (_T_25[3] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:232:33, package.scala:80:42]
    .io_in_a_ready         (_TLBroadcastTracker_3_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_3_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_3_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_3_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_3_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_3_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_3_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_3_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_3_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_3_io_source),
    .io_line               (_TLBroadcastTracker_3_io_line),
    .io_idle               (_TLBroadcastTracker_3_io_idle),
    .io_need_d             (_TLBroadcastTracker_3_io_need_d)
  );
  assign auto_in_a_ready = |_GEN_3;	// @[Broadcast.scala:242:{41,58}]
  assign auto_in_d_valid = out_2_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_d_bits_opcode = muxStateEarly_1 ? out_1_bits_opcode : 3'h0;	// @[Arbiter.scala:118:30, Broadcast.scala:131:21, :132:24, :133:30, Edges.scala:229:27, Mux.scala:27:73]
  assign auto_in_d_bits_param = muxStateEarly_1 ? (auto_out_d_bits_source[6] ? (auto_out_d_bits_opcode[0] ? {1'h0, ~(auto_out_d_bits_source[5])} : 2'h0) : auto_out_d_bits_param) : 2'h0;	// @[Arbiter.scala:118:30, Broadcast.scala:119:37, :131:21, :132:{19,24}, :134:{30,36,51,58}, Bundles.scala:262:74, Edges.scala:106:36, Mux.scala:27:73, ReadyValidCancel.scala:68:19]
  assign auto_in_d_bits_size = muxStateEarly_1 ? auto_out_d_bits_size : 3'h0;	// @[Arbiter.scala:118:30, Edges.scala:229:27, Mux.scala:27:73]
  assign auto_in_d_bits_source = muxStateEarly_1 ? out_1_bits_source : 5'h0;	// @[Arbiter.scala:118:30, Broadcast.scala:131:21, Bundles.scala:260:74, Mux.scala:27:73]
  assign auto_in_d_bits_sink = muxStateEarly_1 ? {|(_T_25[3:2]), _T_25[3] | _T_25[1]} : 2'h0;	// @[Arbiter.scala:118:30, Bundles.scala:262:74, Cat.scala:33:92, Mux.scala:27:73, OneHot.scala:30:18, :31:18, :32:{14,28}, package.scala:80:42]
  assign auto_in_d_bits_denied = muxStateEarly_1 & auto_out_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_d_bits_data = muxStateEarly_1 ? auto_out_d_bits_data : 64'h0;	// @[Arbiter.scala:118:30, Bundles.scala:260:74, Mux.scala:27:73]
  assign auto_in_d_bits_corrupt = muxStateEarly_1 & auto_out_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_a_valid = out_8_valid;	// @[Arbiter.scala:126:29]
  assign auto_out_a_bits_opcode = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_opcode : 3'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_opcode : 3'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_opcode : 3'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Edges.scala:229:27, Mux.scala:27:73]
  assign auto_out_a_bits_param = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_param : 3'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_param : 3'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_param : 3'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_param : 3'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Edges.scala:229:27, Mux.scala:27:73]
  assign auto_out_a_bits_size = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_size : 3'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_size : 3'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_size : 3'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_size : 3'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Edges.scala:229:27, Mux.scala:27:73]
  assign auto_out_a_bits_source = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_source : 7'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_source : 7'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_source : 7'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_source : 7'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_a_bits_address = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_address : 31'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_address : 31'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_address : 31'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_address : 31'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Bundles.scala:260:74, Mux.scala:27:73]
  assign auto_out_a_bits_mask = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_mask : 8'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_mask : 8'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_mask : 8'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_mask : 8'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_a_bits_data = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_data : 64'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_data : 64'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_data : 64'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_data : 64'h0);	// @[Arbiter.scala:118:30, Broadcast.scala:108:15, Bundles.scala:260:74, Mux.scala:27:73]
  assign auto_out_d_ready = x1_d_ready;	// @[Broadcast.scala:129:50]
endmodule

