// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLPLIC(
  input         clock,
                reset,
                auto_int_in_0,
                auto_int_in_1,
                auto_int_in_2,
                auto_int_in_3,
                auto_int_in_4,
                auto_int_in_5,
                auto_int_in_6,
                auto_int_in_7,
                auto_int_in_8,
                auto_int_in_9,
                auto_int_in_10,
                auto_in_a_valid,
  input  [2:0]  auto_in_a_bits_opcode,
  input  [1:0]  auto_in_a_bits_size,
  input  [8:0]  auto_in_a_bits_source,
  input  [27:0] auto_in_a_bits_address,
  input  [7:0]  auto_in_a_bits_mask,
  input  [63:0] auto_in_a_bits_data,
  input         auto_in_d_ready,
  output        auto_int_out_7_0,
                auto_int_out_6_0,
                auto_int_out_5_0,
                auto_int_out_4_0,
                auto_int_out_3_0,
                auto_int_out_2_0,
                auto_int_out_1_0,
                auto_int_out_0_0,
                auto_in_a_ready,
                auto_in_d_valid,
  output [2:0]  auto_in_d_bits_opcode,
  output [1:0]  auto_in_d_bits_size,
  output [8:0]  auto_in_d_bits_source,
  output [63:0] auto_in_d_bits_data
);

  wire        out_woready_25;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_36;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_49;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_14;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_22;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_33;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_19;	// @[RegisterRouter.scala:83:24]
  wire        out_woready_30;	// @[RegisterRouter.scala:83:24]
  wire        _out_rofireMux_T_1;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_960;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_896;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_832;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_768;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_704;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_640;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_576;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_512;	// @[RegisterRouter.scala:83:24]
  wire        completer_5;	// @[Plic.scala:295:35]
  wire [3:0]  completerDev;	// @[RegisterRouter.scala:83:24, package.scala:155:13]
  wire        completer_6;	// @[Plic.scala:295:35]
  wire        completer_2;	// @[Plic.scala:295:35]
  wire        completer_0;	// @[Plic.scala:295:35]
  wire        completer_7;	// @[Plic.scala:295:35]
  wire        completer_3;	// @[Plic.scala:295:35]
  wire        completer_1;	// @[Plic.scala:295:35]
  wire        completer_4;	// @[Plic.scala:295:35]
  wire        _out_back_io_deq_valid;	// @[Decoupled.scala:375:21]
  wire        _out_back_io_deq_bits_read;	// @[Decoupled.scala:375:21]
  wire [22:0] _out_back_io_deq_bits_index;	// @[Decoupled.scala:375:21]
  wire [63:0] _out_back_io_deq_bits_data;	// @[Decoupled.scala:375:21]
  wire [7:0]  _out_back_io_deq_bits_mask;	// @[Decoupled.scala:375:21]
  wire [3:0]  _fanin_7_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_7_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_6_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_6_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_5_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_5_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_4_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_4_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_3_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_3_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_2_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_2_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_1_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_1_io_max;	// @[Plic.scala:184:25]
  wire [3:0]  _fanin_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_io_max;	// @[Plic.scala:184:25]
  wire        _gateways_gateway_10_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_9_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_8_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_7_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_6_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_5_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_4_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_3_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_2_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_1_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_io_plic_valid;	// @[Plic.scala:156:27]
  reg  [2:0]  priority_0;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_1;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_2;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_3;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_4;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_5;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_6;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_7;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_8;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_9;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_10;	// @[Plic.scala:163:31]
  reg  [2:0]  threshold_0;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_1;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_2;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_3;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_4;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_5;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_6;	// @[Plic.scala:166:31]
  reg  [2:0]  threshold_7;	// @[Plic.scala:166:31]
  reg         pending_0;	// @[Plic.scala:168:26]
  reg         pending_1;	// @[Plic.scala:168:26]
  reg         pending_2;	// @[Plic.scala:168:26]
  reg         pending_3;	// @[Plic.scala:168:26]
  reg         pending_4;	// @[Plic.scala:168:26]
  reg         pending_5;	// @[Plic.scala:168:26]
  reg         pending_6;	// @[Plic.scala:168:26]
  reg         pending_7;	// @[Plic.scala:168:26]
  reg         pending_8;	// @[Plic.scala:168:26]
  reg         pending_9;	// @[Plic.scala:168:26]
  reg         pending_10;	// @[Plic.scala:168:26]
  reg  [6:0]  enables_0_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_0_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_1_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_1_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_2_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_2_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_3_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_3_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_4_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_4_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_5_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_5_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_6_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_6_1;	// @[Plic.scala:176:51]
  reg  [6:0]  enables_7_0;	// @[Plic.scala:174:26]
  reg  [3:0]  enables_7_1;	// @[Plic.scala:176:51]
  reg  [3:0]  maxDevs_0;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_1;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_2;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_3;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_4;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_5;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_6;	// @[Plic.scala:181:22]
  reg  [3:0]  maxDevs_7;	// @[Plic.scala:181:22]
  wire [10:0] pendingUInt = {pending_10, pending_9, pending_8, pending_7, pending_6, pending_5, pending_4, pending_3, pending_2, pending_1, pending_0};	// @[Cat.scala:33:92, Plic.scala:168:26]
  reg  [2:0]  x1_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_1_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_2_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_3_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_4_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_5_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_6_0_REG;	// @[Plic.scala:188:45]
  reg  [2:0]  bundleOut_7_0_REG;	// @[Plic.scala:188:45]
  wire [15:0] _completedDevs_T_7 = 16'h1 << completerDev;	// @[OneHot.scala:64:12, RegisterRouter.scala:83:24, package.scala:155:13]
  wire [10:0] _GEN = completer_0 | completer_1 | completer_2 | completer_3 | completer_4 | completer_5 | completer_6 | completer_7 ? _completedDevs_T_7[11:1] : 11'h0;	// @[OneHot.scala:64:{12,27}, Plic.scala:264:{28,48}, :295:35, RegisterRouter.scala:83:24]
  wire        _out_T_45 = {_out_back_io_deq_bits_index[22:19], _out_back_io_deq_bits_index[17:12], _out_back_io_deq_bits_index[8:7], _out_back_io_deq_bits_index[3]} == 13'h0;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire [31:0] _out_womask_T_49 = {{8{_out_back_io_deq_bits_mask[7]}}, {8{_out_back_io_deq_bits_mask[6]}}, {8{_out_back_io_deq_bits_mask[5]}}, {8{_out_back_io_deq_bits_mask[4]}}};	// @[Bitwise.scala:28:17, :77:12, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire        claimer_4 = _out_rofireMux_T_1 & out_backSel_768 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _GEN_0 = {8'h0, completerDev};	// @[Bitwise.scala:77:12, Plic.scala:295:51, RegisterRouter.scala:83:24, package.scala:155:13]
  wire [11:0] _out_completer_4_T = {enables_4_1, enables_4_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_4 = out_woready_14 & (&_out_womask_T_49) & _out_completer_4_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_1 = _out_rofireMux_T_1 & out_backSel_576 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _out_completer_1_T = {enables_1_1, enables_1_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_1 = out_woready_19 & (&_out_womask_T_49) & _out_completer_1_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_3 = _out_rofireMux_T_1 & out_backSel_704 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _out_completer_3_T = {enables_3_1, enables_3_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_3 = out_woready_22 & (&_out_womask_T_49) & _out_completer_3_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_7 = _out_rofireMux_T_1 & out_backSel_960 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _out_completer_7_T = {enables_7_1, enables_7_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_7 = out_woready_25 & (&_out_womask_T_49) & _out_completer_7_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_0 = _out_rofireMux_T_1 & out_backSel_512 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _out_completer_0_T = {enables_0_1, enables_0_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_0 = out_woready_30 & (&_out_womask_T_49) & _out_completer_0_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_2 = _out_rofireMux_T_1 & out_backSel_640 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _out_completer_2_T = {enables_2_1, enables_2_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_2 = out_woready_33 & (&_out_womask_T_49) & _out_completer_2_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_6 = _out_rofireMux_T_1 & out_backSel_896 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  wire [11:0] _out_completer_6_T = {enables_6_1, enables_6_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_6 = out_woready_36 & (&_out_womask_T_49) & _out_completer_6_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire        claimer_5 = _out_rofireMux_T_1 & out_backSel_832 & _out_T_45 & (|_out_womask_T_49);	// @[RegisterRouter.scala:83:24]
  assign completerDev = _out_back_io_deq_bits_data[35:32];	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24, package.scala:155:13]
  wire [11:0] _out_completer_5_T = {enables_5_1, enables_5_0, 1'h0} >> _GEN_0;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :176:51, :295:51]
  assign completer_5 = out_woready_49 & (&_out_womask_T_49) & _out_completer_5_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire [9:0]  out_oindex = {_out_back_io_deq_bits_index[18], _out_back_io_deq_bits_index[11:9], _out_back_io_deq_bits_index[6:4], _out_back_io_deq_bits_index[2:0]};	// @[Cat.scala:33:92, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire [9:0]  _GEN_1 = {_out_back_io_deq_bits_index[18], _out_back_io_deq_bits_index[11:9], _out_back_io_deq_bits_index[6:4], _out_back_io_deq_bits_index[2:0]};	// @[Cat.scala:33:92, Decoupled.scala:375:21, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_512 = _GEN_1 == 10'h200;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_576 = _GEN_1 == 10'h240;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_640 = _GEN_1 == 10'h280;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_704 = _GEN_1 == 10'h2C0;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_768 = _GEN_1 == 10'h300;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_832 = _GEN_1 == 10'h340;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_896 = _GEN_1 == 10'h380;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_960 = _GEN_1 == 10'h3C0;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        _out_wofireMux_T = _out_back_io_deq_valid & auto_in_d_ready;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  assign _out_rofireMux_T_1 = _out_wofireMux_T & _out_back_io_deq_bits_read;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire        _out_wofireMux_T_2 = _out_wofireMux_T & ~_out_back_io_deq_bits_read;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire        out_woready_62 = _out_wofireMux_T_2 & _GEN_1 == 10'h1 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_16 = _out_wofireMux_T_2 & _GEN_1 == 10'h2 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_27 = _out_wofireMux_T_2 & _GEN_1 == 10'h3 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_67 = _out_wofireMux_T_2 & _GEN_1 == 10'h4 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_51 = _out_wofireMux_T_2 & _GEN_1 == 10'h5 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_45 = _out_wofireMux_T_2 & _GEN_1 == 10'h80 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_54 = _out_wofireMux_T_2 & _GEN_1 == 10'h88 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_70 = _out_wofireMux_T_2 & _GEN_1 == 10'h90 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_60 = _out_wofireMux_T_2 & _GEN_1 == 10'h98 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_42 = _out_wofireMux_T_2 & _GEN_1 == 10'hA0 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_65 = _out_wofireMux_T_2 & _GEN_1 == 10'hA8 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_39 = _out_wofireMux_T_2 & _GEN_1 == 10'hB0 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_57 = _out_wofireMux_T_2 & _GEN_1 == 10'hB8 & _out_T_45;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_30 = _out_wofireMux_T_2 & out_backSel_512 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_19 = _out_wofireMux_T_2 & out_backSel_576 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_33 = _out_wofireMux_T_2 & out_backSel_640 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_22 = _out_wofireMux_T_2 & out_backSel_704 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_14 = _out_wofireMux_T_2 & out_backSel_768 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_49 = _out_wofireMux_T_2 & out_backSel_832 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_36 = _out_wofireMux_T_2 & out_backSel_896 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  assign out_woready_25 = _out_wofireMux_T_2 & out_backSel_960 & _out_T_45;	// @[RegisterRouter.scala:83:24]
  wire        _out_out_bits_data_T_23 = out_oindex == 10'h0;	// @[Cat.scala:33:92, MuxLiteral.scala:54:22]
  wire [3:0]  claiming = (claimer_0 ? maxDevs_0 : 4'h0) | (claimer_1 ? maxDevs_1 : 4'h0) | (claimer_2 ? maxDevs_2 : 4'h0) | (claimer_3 ? maxDevs_3 : 4'h0) | (claimer_4 ? maxDevs_4 : 4'h0) | (claimer_5 ? maxDevs_5 : 4'h0) | (claimer_6 ? maxDevs_6 : 4'h0) | (claimer_7 ? maxDevs_7 : 4'h0);	// @[Plic.scala:181:22, :246:{49,92}, RegisterRouter.scala:83:24]
  wire        claimedDevs_1 = claiming == 4'h1;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_2 = claiming == 4'h2;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_3 = claiming == 4'h3;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_4 = claiming == 4'h4;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_5 = claiming == 4'h5;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_6 = claiming == 4'h6;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_7 = claiming == 4'h7;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_8 = claiming == 4'h8;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_9 = claiming == 4'h9;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_10 = claiming == 4'hA;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  wire        claimedDevs_11 = claiming == 4'hB;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:92, :247:62]
  always @(posedge clock) begin
    if (_out_wofireMux_T_2 & _GEN_1 == 10'h0 & _out_T_45 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
      priority_0 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_62 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_1 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_62 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_2 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_16 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_3 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_16 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_4 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_27 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_5 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_27 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_6 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_67 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_7 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_67 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_8 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_51 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_9 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_51 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_10 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_30 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_0 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_19 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_1 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_33 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_2 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_22 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_3 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_14 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_4 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_49 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_5 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_36 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_6 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_25 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_7 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_45 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_0_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_45 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_0_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_54 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_1_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_54 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_1_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_70 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_2_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_70 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_2_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_60 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_3_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_60 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_3_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_42 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_4_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_42 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_4_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_65 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_5_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_65 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_5_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_39 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_6_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_39 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_6_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    if (out_woready_57 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_7_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_57 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_7_1 <= _out_back_io_deq_bits_data[11:8];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    maxDevs_0 <= _fanin_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_1 <= _fanin_1_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_2 <= _fanin_2_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_3 <= _fanin_3_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_4 <= _fanin_4_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_5 <= _fanin_5_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_6 <= _fanin_6_io_dev;	// @[Plic.scala:181:22, :184:25]
    maxDevs_7 <= _fanin_7_io_dev;	// @[Plic.scala:181:22, :184:25]
    x1_0_REG <= _fanin_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_1_0_REG <= _fanin_1_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_2_0_REG <= _fanin_2_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_3_0_REG <= _fanin_3_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_4_0_REG <= _fanin_4_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_5_0_REG <= _fanin_5_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_6_0_REG <= _fanin_6_io_max;	// @[Plic.scala:184:25, :188:45]
    bundleOut_7_0_REG <= _fanin_7_io_max;	// @[Plic.scala:184:25, :188:45]
    if (reset) begin
      pending_0 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_1 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_2 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_3 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_4 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_5 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_6 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_7 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_8 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_9 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_10 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
    end
    else begin
      if (claimedDevs_1 | _gateways_gateway_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_0 <= ~claimedDevs_1;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_2 | _gateways_gateway_1_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_1 <= ~claimedDevs_2;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_3 | _gateways_gateway_2_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_2 <= ~claimedDevs_3;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_4 | _gateways_gateway_3_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_3 <= ~claimedDevs_4;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_5 | _gateways_gateway_4_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_4 <= ~claimedDevs_5;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_6 | _gateways_gateway_5_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_5 <= ~claimedDevs_6;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_7 | _gateways_gateway_6_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_6 <= ~claimedDevs_7;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_8 | _gateways_gateway_7_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_7 <= ~claimedDevs_8;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_9 | _gateways_gateway_8_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_8 <= ~claimedDevs_9;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_10 | _gateways_gateway_9_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_9 <= ~claimedDevs_10;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_11 | _gateways_gateway_10_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_10 <= ~claimedDevs_11;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[Plic.scala:245:11]
      if (~reset & (|({claimer_7, claimer_6, claimer_5, claimer_4, claimer_3, claimer_2, claimer_1, claimer_0} & {claimer_7, claimer_6, claimer_5, claimer_4, claimer_3, claimer_2, claimer_1, claimer_0} - 8'h1))) begin	// @[Plic.scala:245:{11,21,28,46,54}, RegisterRouter.scala:83:24]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:245:11]
          $error("Assertion failed\n    at Plic.scala:245 assert((claimer.asUInt & (claimer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[Plic.scala:245:11]
        if (`STOP_COND_)	// @[Plic.scala:245:11]
          $fatal;	// @[Plic.scala:245:11]
      end
      if (~reset & (|({completer_7, completer_6, completer_5, completer_4, completer_3, completer_2, completer_1, completer_0} & {completer_7, completer_6, completer_5, completer_4, completer_3, completer_2, completer_1, completer_0} - 8'h1))) begin	// @[Plic.scala:262:{11,23,30,50,58}, :295:35]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:262:11]
          $error("Assertion failed\n    at Plic.scala:262 assert((completer.asUInt & (completer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[Plic.scala:262:11]
        if (`STOP_COND_)	// @[Plic.scala:262:11]
          $fatal;	// @[Plic.scala:262:11]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
      if (~reset & completerDev != _out_back_io_deq_bits_data[35:32]) begin	// @[Decoupled.scala:375:21, Plic.scala:292:{19,33}, RegisterRouter.scala:83:24, package.scala:155:13]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:292:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:292 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[Plic.scala:292:19]
        if (`STOP_COND_)	// @[Plic.scala:292:19]
          $fatal;	// @[Plic.scala:292:19]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        priority_0 = _RANDOM_0[2:0];	// @[Plic.scala:163:31]
        priority_1 = _RANDOM_0[5:3];	// @[Plic.scala:163:31]
        priority_2 = _RANDOM_0[8:6];	// @[Plic.scala:163:31]
        priority_3 = _RANDOM_0[11:9];	// @[Plic.scala:163:31]
        priority_4 = _RANDOM_0[14:12];	// @[Plic.scala:163:31]
        priority_5 = _RANDOM_0[17:15];	// @[Plic.scala:163:31]
        priority_6 = _RANDOM_0[20:18];	// @[Plic.scala:163:31]
        priority_7 = _RANDOM_0[23:21];	// @[Plic.scala:163:31]
        priority_8 = _RANDOM_0[26:24];	// @[Plic.scala:163:31]
        priority_9 = _RANDOM_0[29:27];	// @[Plic.scala:163:31]
        priority_10 = {_RANDOM_0[31:30], _RANDOM_1[0]};	// @[Plic.scala:163:31]
        threshold_0 = _RANDOM_1[3:1];	// @[Plic.scala:163:31, :166:31]
        threshold_1 = _RANDOM_1[6:4];	// @[Plic.scala:163:31, :166:31]
        threshold_2 = _RANDOM_1[9:7];	// @[Plic.scala:163:31, :166:31]
        threshold_3 = _RANDOM_1[12:10];	// @[Plic.scala:163:31, :166:31]
        threshold_4 = _RANDOM_1[15:13];	// @[Plic.scala:163:31, :166:31]
        threshold_5 = _RANDOM_1[18:16];	// @[Plic.scala:163:31, :166:31]
        threshold_6 = _RANDOM_1[21:19];	// @[Plic.scala:163:31, :166:31]
        threshold_7 = _RANDOM_1[24:22];	// @[Plic.scala:163:31, :166:31]
        pending_0 = _RANDOM_1[25];	// @[Plic.scala:163:31, :168:26]
        pending_1 = _RANDOM_1[26];	// @[Plic.scala:163:31, :168:26]
        pending_2 = _RANDOM_1[27];	// @[Plic.scala:163:31, :168:26]
        pending_3 = _RANDOM_1[28];	// @[Plic.scala:163:31, :168:26]
        pending_4 = _RANDOM_1[29];	// @[Plic.scala:163:31, :168:26]
        pending_5 = _RANDOM_1[30];	// @[Plic.scala:163:31, :168:26]
        pending_6 = _RANDOM_1[31];	// @[Plic.scala:163:31, :168:26]
        pending_7 = _RANDOM_2[0];	// @[Plic.scala:168:26]
        pending_8 = _RANDOM_2[1];	// @[Plic.scala:168:26]
        pending_9 = _RANDOM_2[2];	// @[Plic.scala:168:26]
        pending_10 = _RANDOM_2[3];	// @[Plic.scala:168:26]
        enables_0_0 = _RANDOM_2[10:4];	// @[Plic.scala:168:26, :174:26]
        enables_0_1 = _RANDOM_2[14:11];	// @[Plic.scala:168:26, :176:51]
        enables_1_0 = _RANDOM_2[21:15];	// @[Plic.scala:168:26, :174:26]
        enables_1_1 = _RANDOM_2[25:22];	// @[Plic.scala:168:26, :176:51]
        enables_2_0 = {_RANDOM_2[31:26], _RANDOM_3[0]};	// @[Plic.scala:168:26, :174:26]
        enables_2_1 = _RANDOM_3[4:1];	// @[Plic.scala:174:26, :176:51]
        enables_3_0 = _RANDOM_3[11:5];	// @[Plic.scala:174:26]
        enables_3_1 = _RANDOM_3[15:12];	// @[Plic.scala:174:26, :176:51]
        enables_4_0 = _RANDOM_3[22:16];	// @[Plic.scala:174:26]
        enables_4_1 = _RANDOM_3[26:23];	// @[Plic.scala:174:26, :176:51]
        enables_5_0 = {_RANDOM_3[31:27], _RANDOM_4[1:0]};	// @[Plic.scala:174:26]
        enables_5_1 = _RANDOM_4[5:2];	// @[Plic.scala:174:26, :176:51]
        enables_6_0 = _RANDOM_4[12:6];	// @[Plic.scala:174:26]
        enables_6_1 = _RANDOM_4[16:13];	// @[Plic.scala:174:26, :176:51]
        enables_7_0 = _RANDOM_4[23:17];	// @[Plic.scala:174:26]
        enables_7_1 = _RANDOM_4[27:24];	// @[Plic.scala:174:26, :176:51]
        maxDevs_0 = _RANDOM_4[31:28];	// @[Plic.scala:174:26, :181:22]
        maxDevs_1 = _RANDOM_5[3:0];	// @[Plic.scala:181:22]
        maxDevs_2 = _RANDOM_5[7:4];	// @[Plic.scala:181:22]
        maxDevs_3 = _RANDOM_5[11:8];	// @[Plic.scala:181:22]
        maxDevs_4 = _RANDOM_5[15:12];	// @[Plic.scala:181:22]
        maxDevs_5 = _RANDOM_5[19:16];	// @[Plic.scala:181:22]
        maxDevs_6 = _RANDOM_5[23:20];	// @[Plic.scala:181:22]
        maxDevs_7 = _RANDOM_5[27:24];	// @[Plic.scala:181:22]
        x1_0_REG = _RANDOM_5[30:28];	// @[Plic.scala:181:22, :188:45]
        bundleOut_1_0_REG = {_RANDOM_5[31], _RANDOM_6[1:0]};	// @[Plic.scala:181:22, :188:45]
        bundleOut_2_0_REG = _RANDOM_6[4:2];	// @[Plic.scala:188:45]
        bundleOut_3_0_REG = _RANDOM_6[7:5];	// @[Plic.scala:188:45]
        bundleOut_4_0_REG = _RANDOM_6[10:8];	// @[Plic.scala:188:45]
        bundleOut_5_0_REG = _RANDOM_6[13:11];	// @[Plic.scala:188:45]
        bundleOut_6_0_REG = _RANDOM_6[16:14];	// @[Plic.scala:188:45]
        bundleOut_7_0_REG = _RANDOM_6[19:17];	// @[Plic.scala:188:45]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  LevelGateway gateways_gateway (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_0),
    .io_plic_ready    (~pending_0),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[0]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_io_plic_valid)
  );
  LevelGateway gateways_gateway_1 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_1),
    .io_plic_ready    (~pending_1),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[1]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_1_io_plic_valid)
  );
  LevelGateway gateways_gateway_2 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_2),
    .io_plic_ready    (~pending_2),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[2]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_2_io_plic_valid)
  );
  LevelGateway gateways_gateway_3 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_3),
    .io_plic_ready    (~pending_3),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[3]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_3_io_plic_valid)
  );
  LevelGateway gateways_gateway_4 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_4),
    .io_plic_ready    (~pending_4),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[4]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_4_io_plic_valid)
  );
  LevelGateway gateways_gateway_5 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_5),
    .io_plic_ready    (~pending_5),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[5]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_5_io_plic_valid)
  );
  LevelGateway gateways_gateway_6 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_6),
    .io_plic_ready    (~pending_6),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[6]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_6_io_plic_valid)
  );
  LevelGateway gateways_gateway_7 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_7),
    .io_plic_ready    (~pending_7),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[7]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_7_io_plic_valid)
  );
  LevelGateway gateways_gateway_8 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_8),
    .io_plic_ready    (~pending_8),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[8]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_8_io_plic_valid)
  );
  LevelGateway gateways_gateway_9 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_9),
    .io_plic_ready    (~pending_9),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[9]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_9_io_plic_valid)
  );
  LevelGateway gateways_gateway_10 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_10),
    .io_plic_ready    (~pending_10),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[10]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_10_io_plic_valid)
  );
  PLICFanIn fanin (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_0_1, enables_0_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_io_dev),
    .io_max     (_fanin_io_max)
  );
  PLICFanIn fanin_1 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_1_1, enables_1_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_1_io_dev),
    .io_max     (_fanin_1_io_max)
  );
  PLICFanIn fanin_2 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_2_1, enables_2_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_2_io_dev),
    .io_max     (_fanin_2_io_max)
  );
  PLICFanIn fanin_3 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_3_1, enables_3_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_3_io_dev),
    .io_max     (_fanin_3_io_max)
  );
  PLICFanIn fanin_4 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_4_1, enables_4_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_4_io_dev),
    .io_max     (_fanin_4_io_max)
  );
  PLICFanIn fanin_5 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_5_1, enables_5_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_5_io_dev),
    .io_max     (_fanin_5_io_max)
  );
  PLICFanIn fanin_6 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_6_1, enables_6_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_6_io_dev),
    .io_max     (_fanin_6_io_max)
  );
  PLICFanIn fanin_7 (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_ip      ({enables_7_1, enables_7_0} & pendingUInt),	// @[Cat.scala:33:92, Plic.scala:174:26, :176:51, :186:40]
    .io_dev     (_fanin_7_io_dev),
    .io_max     (_fanin_7_io_max)
  );
  Queue_73 out_back (	// @[Decoupled.scala:375:21]
    .clock                               (clock),
    .reset                               (reset),
    .io_enq_valid                        (auto_in_a_valid),
    .io_enq_bits_read                    (auto_in_a_bits_opcode == 3'h4),	// @[RegisterRouter.scala:72:36]
    .io_enq_bits_index                   (auto_in_a_bits_address[25:3]),	// @[Edges.scala:192:34, RegisterRouter.scala:73:19]
    .io_enq_bits_data                    (auto_in_a_bits_data),
    .io_enq_bits_mask                    (auto_in_a_bits_mask),
    .io_enq_bits_extra_tlrr_extra_source (auto_in_a_bits_source),
    .io_enq_bits_extra_tlrr_extra_size   (auto_in_a_bits_size),
    .io_deq_ready                        (auto_in_d_ready),
    .io_enq_ready                        (auto_in_a_ready),
    .io_deq_valid                        (_out_back_io_deq_valid),
    .io_deq_bits_read                    (_out_back_io_deq_bits_read),
    .io_deq_bits_index                   (_out_back_io_deq_bits_index),
    .io_deq_bits_data                    (_out_back_io_deq_bits_data),
    .io_deq_bits_mask                    (_out_back_io_deq_bits_mask),
    .io_deq_bits_extra_tlrr_extra_source (auto_in_d_bits_source),
    .io_deq_bits_extra_tlrr_extra_size   (auto_in_d_bits_size)
  );
  assign auto_int_out_7_0 = bundleOut_7_0_REG > threshold_7;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_6_0 = bundleOut_6_0_REG > threshold_6;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_5_0 = bundleOut_5_0_REG > threshold_5;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_4_0 = bundleOut_4_0_REG > threshold_4;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_3_0 = bundleOut_3_0_REG > threshold_3;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_2_0 = bundleOut_2_0_REG > threshold_2;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_1_0 = bundleOut_1_0_REG > threshold_1;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_int_out_0_0 = x1_0_REG > threshold_0;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_in_d_valid = _out_back_io_deq_valid;	// @[Decoupled.scala:375:21]
  assign auto_in_d_bits_opcode = {2'h0, _out_back_io_deq_bits_read};	// @[Decoupled.scala:375:21, MuxLiteral.scala:54:22, RegisterRouter.scala:98:19]
  assign auto_in_d_bits_data =
    ~(_out_out_bits_data_T_23 | out_oindex == 10'h1 | out_oindex == 10'h2 | out_oindex == 10'h3 | out_oindex == 10'h4 | out_oindex == 10'h5 | out_oindex == 10'h40 | out_oindex == 10'h80 | out_oindex == 10'h88 | out_oindex == 10'h90 | out_oindex == 10'h98 | out_oindex == 10'hA0 | out_oindex == 10'hA8 | out_oindex == 10'hB0 | out_oindex == 10'hB8 | out_oindex == 10'h200 | out_oindex == 10'h240 | out_oindex == 10'h280 | out_oindex == 10'h2C0 | out_oindex == 10'h300 | out_oindex == 10'h340 | out_oindex == 10'h380 | out_oindex == 10'h3C0) | _out_T_45
      ? (_out_out_bits_data_T_23 ? {29'h0, priority_0, 32'h0} : out_oindex == 10'h1 ? {29'h0, priority_2, 29'h0, priority_1} : out_oindex == 10'h2 ? {29'h0, priority_4, 29'h0, priority_3} : out_oindex == 10'h3 ? {29'h0, priority_6, 29'h0, priority_5} : out_oindex == 10'h4 ? {29'h0, priority_8, 29'h0, priority_7} : out_oindex == 10'h5 ? {29'h0, priority_10, 29'h0, priority_9} : out_oindex == 10'h40 ? {52'h0, pending_10, pending_9, pending_8, pending_7, pending_6, pending_5, pending_4, pending_3, pending_2, pending_1, pending_0, 1'h0} : out_oindex == 10'h80 ? {52'h0, enables_0_1, enables_0_0, 1'h0} : out_oindex == 10'h88 ? {52'h0, enables_1_1, enables_1_0, 1'h0} : out_oindex == 10'h90 ? {52'h0, enables_2_1, enables_2_0, 1'h0} : out_oindex == 10'h98 ? {52'h0, enables_3_1, enables_3_0, 1'h0} : out_oindex == 10'hA0 ? {52'h0, enables_4_1, enables_4_0, 1'h0} : out_oindex == 10'hA8 ? {52'h0, enables_5_1, enables_5_0, 1'h0} : out_oindex == 10'hB0 ? {52'h0, enables_6_1, enables_6_0, 1'h0} : out_oindex == 10'hB8 ? {52'h0, enables_7_1, enables_7_0, 1'h0} : out_oindex == 10'h200 ? {28'h0, maxDevs_0, 29'h0, threshold_0} : out_oindex == 10'h240 ? {28'h0, maxDevs_1, 29'h0, threshold_1} : out_oindex == 10'h280 ? {28'h0, maxDevs_2, 29'h0, threshold_2} : out_oindex == 10'h2C0 ? {28'h0, maxDevs_3, 29'h0, threshold_3} : out_oindex == 10'h300 ? {28'h0, maxDevs_4, 29'h0, threshold_4} : out_oindex == 10'h340 ? {28'h0, maxDevs_5, 29'h0, threshold_5} : out_oindex == 10'h380 ? {28'h0, maxDevs_6, 29'h0, threshold_6} : out_oindex == 10'h3C0 ? {28'h0, maxDevs_7, 29'h0, threshold_7} : 64'h0)
      : 64'h0;	// @[Cat.scala:33:92, MuxLiteral.scala:52:28, :54:{22,28}, Plic.scala:163:31, :166:31, :168:26, :174:26, :176:51, :181:22, RegisterRouter.scala:83:24]
endmodule

